// <auto-generated />
using System;
using Altkom.Shop.DbRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Altkom.Shop.DbRepositories.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20190913052737_AddOrdersSeedData")]
    partial class AddOrdersSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime?>("DeliveredDate");

                    b.Property<string>("Number");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 12,
                            Number = "ZAM 499",
                            OrderDate = new DateTime(2017, 1, 12, 10, 9, 47, 911, DateTimeKind.Local).AddTicks(8576),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 7,
                            Number = "ZAM 916",
                            OrderDate = new DateTime(2019, 7, 13, 21, 57, 31, 982, DateTimeKind.Local).AddTicks(5588),
                            Status = 4
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 11,
                            Number = "ZAM 786",
                            OrderDate = new DateTime(2017, 11, 1, 23, 5, 18, 353, DateTimeKind.Local).AddTicks(3428),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            Number = "ZAM 761",
                            OrderDate = new DateTime(2018, 8, 24, 8, 39, 12, 724, DateTimeKind.Local).AddTicks(4288),
                            Status = 3
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 10,
                            Number = "ZAM 32",
                            OrderDate = new DateTime(2018, 8, 20, 17, 48, 27, 315, DateTimeKind.Local).AddTicks(891),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 14,
                            Number = "ZAM 76",
                            OrderDate = new DateTime(2016, 11, 27, 18, 5, 6, 969, DateTimeKind.Local).AddTicks(5858),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 6,
                            Number = "ZAM 442",
                            OrderDate = new DateTime(2018, 5, 14, 18, 38, 18, 205, DateTimeKind.Local).AddTicks(1800),
                            Status = 4
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 2,
                            Number = "ZAM 829",
                            OrderDate = new DateTime(2018, 1, 8, 10, 31, 15, 821, DateTimeKind.Local).AddTicks(6100),
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 2,
                            Number = "ZAM 213",
                            OrderDate = new DateTime(2018, 10, 26, 19, 13, 11, 656, DateTimeKind.Local).AddTicks(7183),
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 4,
                            Number = "ZAM 151",
                            OrderDate = new DateTime(2017, 9, 15, 4, 22, 12, 193, DateTimeKind.Local).AddTicks(1737),
                            Status = 4
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 7,
                            Number = "ZAM 104",
                            OrderDate = new DateTime(2018, 11, 3, 12, 29, 50, 448, DateTimeKind.Local).AddTicks(9766),
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 5,
                            Number = "ZAM 845",
                            OrderDate = new DateTime(2019, 8, 25, 9, 7, 32, 570, DateTimeKind.Local).AddTicks(5341),
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 6,
                            Number = "ZAM 426",
                            OrderDate = new DateTime(2016, 9, 22, 6, 31, 45, 367, DateTimeKind.Local).AddTicks(7226),
                            Status = 3
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 8,
                            Number = "ZAM 286",
                            OrderDate = new DateTime(2019, 5, 28, 22, 30, 41, 602, DateTimeKind.Local).AddTicks(8068),
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 7,
                            Number = "ZAM 515",
                            OrderDate = new DateTime(2018, 8, 6, 17, 48, 22, 862, DateTimeKind.Local).AddTicks(2509),
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 4,
                            Number = "ZAM 228",
                            OrderDate = new DateTime(2018, 1, 10, 18, 4, 21, 431, DateTimeKind.Local).AddTicks(264),
                            Status = 3
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 7,
                            Number = "ZAM 353",
                            OrderDate = new DateTime(2017, 1, 8, 9, 26, 37, 32, DateTimeKind.Local).AddTicks(9846),
                            Status = 2
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 6,
                            Number = "ZAM 909",
                            OrderDate = new DateTime(2018, 2, 15, 19, 6, 10, 837, DateTimeKind.Local).AddTicks(7108),
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 12,
                            Number = "ZAM 449",
                            OrderDate = new DateTime(2017, 2, 25, 23, 10, 29, 904, DateTimeKind.Local).AddTicks(556),
                            Status = 2
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 6,
                            Number = "ZAM 275",
                            OrderDate = new DateTime(2016, 12, 26, 9, 26, 9, 218, DateTimeKind.Local).AddTicks(4610),
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 12,
                            Number = "ZAM 57",
                            OrderDate = new DateTime(2018, 4, 4, 5, 41, 0, 58, DateTimeKind.Local).AddTicks(4596),
                            Status = 4
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 2,
                            Number = "ZAM 776",
                            OrderDate = new DateTime(2017, 1, 18, 10, 50, 43, 706, DateTimeKind.Local).AddTicks(4964),
                            Status = 4
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 11,
                            Number = "ZAM 240",
                            OrderDate = new DateTime(2017, 1, 26, 11, 11, 48, 126, DateTimeKind.Local).AddTicks(4779),
                            Status = 2
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 8,
                            Number = "ZAM 277",
                            OrderDate = new DateTime(2018, 5, 25, 10, 4, 58, 712, DateTimeKind.Local).AddTicks(5802),
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 14,
                            Number = "ZAM 626",
                            OrderDate = new DateTime(2018, 5, 30, 4, 59, 49, 803, DateTimeKind.Local).AddTicks(8369),
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 13,
                            Number = "ZAM 500",
                            OrderDate = new DateTime(2016, 12, 9, 4, 51, 27, 862, DateTimeKind.Local).AddTicks(4468),
                            Status = 2
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 7,
                            Number = "ZAM 896",
                            OrderDate = new DateTime(2018, 6, 12, 7, 35, 29, 980, DateTimeKind.Local).AddTicks(625),
                            Status = 4
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 9,
                            Number = "ZAM 529",
                            OrderDate = new DateTime(2018, 11, 27, 7, 2, 26, 298, DateTimeKind.Local).AddTicks(3685),
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 11,
                            Number = "ZAM 235",
                            OrderDate = new DateTime(2016, 10, 21, 19, 0, 18, 445, DateTimeKind.Local).AddTicks(5350),
                            Status = 2
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 7,
                            Number = "ZAM 623",
                            OrderDate = new DateTime(2017, 3, 24, 13, 37, 20, 501, DateTimeKind.Local).AddTicks(2299),
                            Status = 2
                        },
                        new
                        {
                            Id = 31,
                            CustomerId = 1,
                            Number = "ZAM 64",
                            OrderDate = new DateTime(2018, 6, 29, 2, 15, 35, 147, DateTimeKind.Local).AddTicks(5892),
                            Status = 1
                        },
                        new
                        {
                            Id = 32,
                            CustomerId = 1,
                            Number = "ZAM 962",
                            OrderDate = new DateTime(2018, 10, 4, 2, 16, 50, 958, DateTimeKind.Local).AddTicks(1251),
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            CustomerId = 12,
                            Number = "ZAM 841",
                            OrderDate = new DateTime(2019, 8, 17, 15, 19, 43, 58, DateTimeKind.Local).AddTicks(8733),
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            CustomerId = 2,
                            Number = "ZAM 788",
                            OrderDate = new DateTime(2019, 2, 27, 1, 18, 41, 33, DateTimeKind.Local).AddTicks(7086),
                            Status = 4
                        },
                        new
                        {
                            Id = 35,
                            CustomerId = 5,
                            Number = "ZAM 42",
                            OrderDate = new DateTime(2019, 8, 6, 21, 16, 53, 446, DateTimeKind.Local).AddTicks(6540),
                            Status = 4
                        },
                        new
                        {
                            Id = 36,
                            CustomerId = 14,
                            Number = "ZAM 948",
                            OrderDate = new DateTime(2018, 7, 10, 0, 43, 29, 642, DateTimeKind.Local).AddTicks(1898),
                            Status = 2
                        },
                        new
                        {
                            Id = 37,
                            CustomerId = 5,
                            Number = "ZAM 585",
                            OrderDate = new DateTime(2016, 11, 2, 20, 12, 38, 579, DateTimeKind.Local).AddTicks(7799),
                            Status = 2
                        },
                        new
                        {
                            Id = 38,
                            CustomerId = 12,
                            Number = "ZAM 20",
                            OrderDate = new DateTime(2018, 11, 30, 1, 39, 20, 218, DateTimeKind.Local).AddTicks(6342),
                            Status = 4
                        },
                        new
                        {
                            Id = 39,
                            CustomerId = 2,
                            Number = "ZAM 980",
                            OrderDate = new DateTime(2017, 10, 2, 23, 8, 39, 395, DateTimeKind.Local).AddTicks(8550),
                            Status = 4
                        },
                        new
                        {
                            Id = 40,
                            CustomerId = 9,
                            Number = "ZAM 694",
                            OrderDate = new DateTime(2018, 6, 23, 8, 18, 41, 528, DateTimeKind.Local).AddTicks(4356),
                            Status = 4
                        },
                        new
                        {
                            Id = 41,
                            CustomerId = 8,
                            Number = "ZAM 329",
                            OrderDate = new DateTime(2016, 12, 7, 20, 34, 52, 229, DateTimeKind.Local).AddTicks(5715),
                            Status = 2
                        },
                        new
                        {
                            Id = 42,
                            CustomerId = 1,
                            Number = "ZAM 102",
                            OrderDate = new DateTime(2018, 5, 11, 0, 35, 36, 921, DateTimeKind.Local).AddTicks(1787),
                            Status = 4
                        },
                        new
                        {
                            Id = 43,
                            CustomerId = 9,
                            Number = "ZAM 41",
                            OrderDate = new DateTime(2018, 11, 11, 14, 14, 39, 638, DateTimeKind.Local).AddTicks(4384),
                            Status = 3
                        },
                        new
                        {
                            Id = 44,
                            CustomerId = 10,
                            Number = "ZAM 884",
                            OrderDate = new DateTime(2019, 6, 2, 12, 30, 53, 925, DateTimeKind.Local).AddTicks(8386),
                            Status = 2
                        },
                        new
                        {
                            Id = 45,
                            CustomerId = 1,
                            Number = "ZAM 817",
                            OrderDate = new DateTime(2018, 12, 10, 12, 55, 56, 245, DateTimeKind.Local).AddTicks(5155),
                            Status = 2
                        },
                        new
                        {
                            Id = 46,
                            CustomerId = 9,
                            Number = "ZAM 767",
                            OrderDate = new DateTime(2017, 5, 13, 12, 40, 3, 307, DateTimeKind.Local).AddTicks(2957),
                            Status = 4
                        },
                        new
                        {
                            Id = 47,
                            CustomerId = 2,
                            Number = "ZAM 102",
                            OrderDate = new DateTime(2018, 8, 12, 20, 1, 2, 828, DateTimeKind.Local).AddTicks(9717),
                            Status = 4
                        },
                        new
                        {
                            Id = 48,
                            CustomerId = 9,
                            Number = "ZAM 293",
                            OrderDate = new DateTime(2017, 3, 21, 11, 46, 12, 418, DateTimeKind.Local).AddTicks(8108),
                            Status = 2
                        },
                        new
                        {
                            Id = 49,
                            CustomerId = 1,
                            Number = "ZAM 95",
                            OrderDate = new DateTime(2018, 8, 14, 7, 3, 37, 511, DateTimeKind.Local).AddTicks(926),
                            Status = 0
                        },
                        new
                        {
                            Id = 50,
                            CustomerId = 2,
                            Number = "ZAM 797",
                            OrderDate = new DateTime(2019, 6, 14, 17, 7, 30, 988, DateTimeKind.Local).AddTicks(7710),
                            Status = 4
                        },
                        new
                        {
                            Id = 51,
                            CustomerId = 11,
                            Number = "ZAM 132",
                            OrderDate = new DateTime(2018, 3, 21, 8, 27, 8, 532, DateTimeKind.Local).AddTicks(2824),
                            Status = 1
                        },
                        new
                        {
                            Id = 52,
                            CustomerId = 13,
                            Number = "ZAM 559",
                            OrderDate = new DateTime(2018, 9, 11, 6, 4, 49, 526, DateTimeKind.Local).AddTicks(5762),
                            Status = 4
                        },
                        new
                        {
                            Id = 53,
                            CustomerId = 7,
                            Number = "ZAM 128",
                            OrderDate = new DateTime(2019, 1, 16, 23, 19, 26, 257, DateTimeKind.Local).AddTicks(3323),
                            Status = 1
                        },
                        new
                        {
                            Id = 54,
                            CustomerId = 8,
                            Number = "ZAM 962",
                            OrderDate = new DateTime(2016, 11, 26, 5, 52, 53, 820, DateTimeKind.Local).AddTicks(2657),
                            Status = 4
                        },
                        new
                        {
                            Id = 55,
                            CustomerId = 11,
                            Number = "ZAM 928",
                            OrderDate = new DateTime(2019, 8, 24, 16, 36, 14, 281, DateTimeKind.Local).AddTicks(9282),
                            Status = 2
                        },
                        new
                        {
                            Id = 56,
                            CustomerId = 3,
                            Number = "ZAM 583",
                            OrderDate = new DateTime(2017, 8, 26, 6, 14, 33, 647, DateTimeKind.Local).AddTicks(6225),
                            Status = 3
                        },
                        new
                        {
                            Id = 57,
                            CustomerId = 8,
                            Number = "ZAM 837",
                            OrderDate = new DateTime(2019, 6, 28, 3, 1, 54, 196, DateTimeKind.Local).AddTicks(6604),
                            Status = 2
                        },
                        new
                        {
                            Id = 58,
                            CustomerId = 11,
                            Number = "ZAM 66",
                            OrderDate = new DateTime(2018, 3, 20, 9, 9, 56, 791, DateTimeKind.Local).AddTicks(4420),
                            Status = 4
                        },
                        new
                        {
                            Id = 59,
                            CustomerId = 4,
                            Number = "ZAM 380",
                            OrderDate = new DateTime(2018, 10, 8, 6, 26, 11, 774, DateTimeKind.Local).AddTicks(5655),
                            Status = 4
                        },
                        new
                        {
                            Id = 60,
                            CustomerId = 11,
                            Number = "ZAM 509",
                            OrderDate = new DateTime(2018, 12, 8, 23, 29, 11, 396, DateTimeKind.Local).AddTicks(7307),
                            Status = 0
                        },
                        new
                        {
                            Id = 61,
                            CustomerId = 2,
                            Number = "ZAM 444",
                            OrderDate = new DateTime(2016, 10, 5, 13, 54, 53, 143, DateTimeKind.Local).AddTicks(3881),
                            Status = 0
                        },
                        new
                        {
                            Id = 62,
                            CustomerId = 3,
                            Number = "ZAM 547",
                            OrderDate = new DateTime(2019, 9, 10, 16, 24, 40, 465, DateTimeKind.Local).AddTicks(5997),
                            Status = 3
                        },
                        new
                        {
                            Id = 63,
                            CustomerId = 11,
                            Number = "ZAM 547",
                            OrderDate = new DateTime(2018, 4, 6, 8, 51, 51, 587, DateTimeKind.Local).AddTicks(9709),
                            Status = 0
                        },
                        new
                        {
                            Id = 64,
                            CustomerId = 7,
                            Number = "ZAM 681",
                            OrderDate = new DateTime(2019, 4, 19, 15, 50, 59, 137, DateTimeKind.Local).AddTicks(5229),
                            Status = 2
                        },
                        new
                        {
                            Id = 65,
                            CustomerId = 7,
                            Number = "ZAM 733",
                            OrderDate = new DateTime(2019, 7, 12, 20, 0, 35, 618, DateTimeKind.Local).AddTicks(6417),
                            Status = 4
                        },
                        new
                        {
                            Id = 66,
                            CustomerId = 9,
                            Number = "ZAM 842",
                            OrderDate = new DateTime(2018, 7, 6, 16, 13, 40, 25, DateTimeKind.Local).AddTicks(7032),
                            Status = 4
                        },
                        new
                        {
                            Id = 67,
                            CustomerId = 10,
                            Number = "ZAM 346",
                            OrderDate = new DateTime(2018, 1, 22, 17, 23, 18, 416, DateTimeKind.Local).AddTicks(4425),
                            Status = 0
                        },
                        new
                        {
                            Id = 68,
                            CustomerId = 10,
                            Number = "ZAM 57",
                            OrderDate = new DateTime(2018, 1, 28, 11, 22, 45, 83, DateTimeKind.Local).AddTicks(6856),
                            Status = 0
                        },
                        new
                        {
                            Id = 69,
                            CustomerId = 9,
                            Number = "ZAM 998",
                            OrderDate = new DateTime(2017, 10, 15, 22, 27, 22, 491, DateTimeKind.Local).AddTicks(4299),
                            Status = 1
                        },
                        new
                        {
                            Id = 70,
                            CustomerId = 12,
                            Number = "ZAM 673",
                            OrderDate = new DateTime(2017, 8, 21, 8, 51, 49, 117, DateTimeKind.Local).AddTicks(5197),
                            Status = 3
                        },
                        new
                        {
                            Id = 71,
                            CustomerId = 9,
                            Number = "ZAM 399",
                            OrderDate = new DateTime(2018, 9, 14, 18, 52, 44, 222, DateTimeKind.Local).AddTicks(8000),
                            Status = 4
                        },
                        new
                        {
                            Id = 72,
                            CustomerId = 4,
                            Number = "ZAM 397",
                            OrderDate = new DateTime(2019, 6, 1, 12, 28, 34, 327, DateTimeKind.Local).AddTicks(964),
                            Status = 0
                        },
                        new
                        {
                            Id = 73,
                            CustomerId = 7,
                            Number = "ZAM 757",
                            OrderDate = new DateTime(2018, 6, 2, 21, 58, 51, 935, DateTimeKind.Local).AddTicks(6436),
                            Status = 2
                        },
                        new
                        {
                            Id = 74,
                            CustomerId = 1,
                            Number = "ZAM 351",
                            OrderDate = new DateTime(2018, 2, 7, 12, 41, 3, 412, DateTimeKind.Local).AddTicks(770),
                            Status = 4
                        },
                        new
                        {
                            Id = 75,
                            CustomerId = 1,
                            Number = "ZAM 160",
                            OrderDate = new DateTime(2018, 7, 26, 8, 59, 20, 506, DateTimeKind.Local).AddTicks(363),
                            Status = 3
                        },
                        new
                        {
                            Id = 76,
                            CustomerId = 1,
                            Number = "ZAM 942",
                            OrderDate = new DateTime(2019, 8, 20, 7, 5, 48, 90, DateTimeKind.Local).AddTicks(3623),
                            Status = 0
                        },
                        new
                        {
                            Id = 77,
                            CustomerId = 1,
                            Number = "ZAM 439",
                            OrderDate = new DateTime(2018, 6, 4, 7, 37, 45, 460, DateTimeKind.Local).AddTicks(9363),
                            Status = 3
                        },
                        new
                        {
                            Id = 78,
                            CustomerId = 1,
                            Number = "ZAM 839",
                            OrderDate = new DateTime(2016, 11, 5, 22, 31, 0, 320, DateTimeKind.Local).AddTicks(4143),
                            Status = 3
                        },
                        new
                        {
                            Id = 79,
                            CustomerId = 8,
                            Number = "ZAM 391",
                            OrderDate = new DateTime(2019, 6, 28, 19, 22, 32, 362, DateTimeKind.Local).AddTicks(2342),
                            Status = 0
                        },
                        new
                        {
                            Id = 80,
                            CustomerId = 4,
                            Number = "ZAM 421",
                            OrderDate = new DateTime(2018, 12, 30, 6, 22, 41, 486, DateTimeKind.Local).AddTicks(8728),
                            Status = 1
                        },
                        new
                        {
                            Id = 81,
                            CustomerId = 9,
                            Number = "ZAM 493",
                            OrderDate = new DateTime(2017, 4, 3, 11, 11, 25, 844, DateTimeKind.Local).AddTicks(2143),
                            Status = 4
                        },
                        new
                        {
                            Id = 82,
                            CustomerId = 7,
                            Number = "ZAM 2",
                            OrderDate = new DateTime(2017, 12, 6, 7, 33, 3, 87, DateTimeKind.Local).AddTicks(1186),
                            Status = 1
                        },
                        new
                        {
                            Id = 83,
                            CustomerId = 5,
                            Number = "ZAM 713",
                            OrderDate = new DateTime(2018, 12, 15, 22, 44, 45, 40, DateTimeKind.Local).AddTicks(5722),
                            Status = 2
                        },
                        new
                        {
                            Id = 84,
                            CustomerId = 6,
                            Number = "ZAM 959",
                            OrderDate = new DateTime(2017, 9, 13, 11, 57, 22, 132, DateTimeKind.Local).AddTicks(1931),
                            Status = 4
                        },
                        new
                        {
                            Id = 85,
                            CustomerId = 14,
                            Number = "ZAM 228",
                            OrderDate = new DateTime(2016, 10, 15, 22, 3, 59, 609, DateTimeKind.Local).AddTicks(7465),
                            Status = 0
                        },
                        new
                        {
                            Id = 86,
                            CustomerId = 12,
                            Number = "ZAM 314",
                            OrderDate = new DateTime(2019, 9, 1, 18, 58, 14, 166, DateTimeKind.Local).AddTicks(5975),
                            Status = 2
                        },
                        new
                        {
                            Id = 87,
                            CustomerId = 4,
                            Number = "ZAM 651",
                            OrderDate = new DateTime(2018, 3, 20, 9, 15, 16, 324, DateTimeKind.Local).AddTicks(5220),
                            Status = 0
                        },
                        new
                        {
                            Id = 88,
                            CustomerId = 13,
                            Number = "ZAM 443",
                            OrderDate = new DateTime(2018, 6, 15, 21, 15, 47, 95, DateTimeKind.Local).AddTicks(7327),
                            Status = 3
                        },
                        new
                        {
                            Id = 89,
                            CustomerId = 2,
                            Number = "ZAM 142",
                            OrderDate = new DateTime(2018, 4, 7, 10, 44, 37, 894, DateTimeKind.Local).AddTicks(4846),
                            Status = 2
                        },
                        new
                        {
                            Id = 90,
                            CustomerId = 12,
                            Number = "ZAM 128",
                            OrderDate = new DateTime(2018, 4, 11, 9, 51, 15, 907, DateTimeKind.Local).AddTicks(1070),
                            Status = 0
                        },
                        new
                        {
                            Id = 91,
                            CustomerId = 9,
                            Number = "ZAM 103",
                            OrderDate = new DateTime(2018, 10, 3, 3, 1, 32, 659, DateTimeKind.Local).AddTicks(8325),
                            Status = 1
                        },
                        new
                        {
                            Id = 92,
                            CustomerId = 11,
                            Number = "ZAM 508",
                            OrderDate = new DateTime(2018, 4, 3, 2, 25, 55, 727, DateTimeKind.Local).AddTicks(7928),
                            Status = 0
                        },
                        new
                        {
                            Id = 93,
                            CustomerId = 7,
                            Number = "ZAM 178",
                            OrderDate = new DateTime(2017, 7, 23, 19, 39, 55, 356, DateTimeKind.Local).AddTicks(344),
                            Status = 1
                        },
                        new
                        {
                            Id = 94,
                            CustomerId = 7,
                            Number = "ZAM 88",
                            OrderDate = new DateTime(2018, 11, 26, 0, 37, 59, 273, DateTimeKind.Local).AddTicks(1246),
                            Status = 4
                        },
                        new
                        {
                            Id = 95,
                            CustomerId = 8,
                            Number = "ZAM 409",
                            OrderDate = new DateTime(2019, 6, 8, 12, 3, 49, 445, DateTimeKind.Local).AddTicks(5209),
                            Status = 4
                        },
                        new
                        {
                            Id = 96,
                            CustomerId = 5,
                            Number = "ZAM 530",
                            OrderDate = new DateTime(2019, 7, 28, 19, 21, 18, 419, DateTimeKind.Local).AddTicks(4353),
                            Status = 0
                        },
                        new
                        {
                            Id = 97,
                            CustomerId = 7,
                            Number = "ZAM 621",
                            OrderDate = new DateTime(2018, 2, 21, 19, 12, 23, 251, DateTimeKind.Local).AddTicks(3093),
                            Status = 0
                        },
                        new
                        {
                            Id = 98,
                            CustomerId = 11,
                            Number = "ZAM 160",
                            OrderDate = new DateTime(2017, 5, 27, 1, 30, 37, 844, DateTimeKind.Local).AddTicks(8632),
                            Status = 1
                        },
                        new
                        {
                            Id = 99,
                            CustomerId = 14,
                            Number = "ZAM 967",
                            OrderDate = new DateTime(2018, 10, 20, 18, 31, 45, 647, DateTimeKind.Local).AddTicks(4779),
                            Status = 4
                        },
                        new
                        {
                            Id = 100,
                            CustomerId = 3,
                            Number = "ZAM 680",
                            OrderDate = new DateTime(2017, 4, 2, 1, 10, 37, 268, DateTimeKind.Local).AddTicks(8026),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<short>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Product", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<string>("Barcode");

                    b.Property<string>("Color")
                        .HasMaxLength(20);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasDiscriminator().HasValue("Product");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Name = "Fantastic Granite Pants",
                            UnitPrice = 40.959275289419728m,
                            Barcode = "4523977196850",
                            Color = "mint green",
                            SerialNumber = "35085492"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Generic Metal Fish",
                            UnitPrice = 29.115057303158122m,
                            Barcode = "2550374164368",
                            Color = "fuchsia",
                            SerialNumber = "25730371"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Sleek Plastic Bike",
                            UnitPrice = 87.707788642825471m,
                            Barcode = "8048595784143",
                            Color = "sky blue",
                            SerialNumber = "17811699"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Intelligent Plastic Tuna",
                            UnitPrice = 81.313919344131814m,
                            Barcode = "7632843830235",
                            Color = "lavender",
                            SerialNumber = "25669688"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Fantastic Plastic Mouse",
                            UnitPrice = 14.301364281820813m,
                            Barcode = "5518333445191",
                            Color = "grey",
                            SerialNumber = "63830217"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Sleek Granite Salad",
                            UnitPrice = 75.974670754733827m,
                            Barcode = "0395485449728",
                            Color = "salmon",
                            SerialNumber = "35496793"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Practical Metal Chips",
                            UnitPrice = 74.736476324375986m,
                            Barcode = "7471209065702",
                            Color = "plum",
                            SerialNumber = "37059743"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Awesome Rubber Car",
                            UnitPrice = 74.450739403465138m,
                            Barcode = "8147511333899",
                            Color = "salmon",
                            SerialNumber = "04140658"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Handmade Cotton Towels",
                            UnitPrice = 5.3213496684661864m,
                            Barcode = "6376220141309",
                            Color = "cyan",
                            SerialNumber = "51454470"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Unbranded Wooden Hat",
                            UnitPrice = 91.463964605454286m,
                            Barcode = "5078938465029",
                            Color = "sky blue",
                            SerialNumber = "34103654"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Ergonomic Wooden Bacon",
                            UnitPrice = 1.70217751837436929m,
                            Barcode = "2033659672111",
                            Color = "fuchsia",
                            SerialNumber = "51103941"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Rustic Wooden Mouse",
                            UnitPrice = 13.125591175223548m,
                            Barcode = "3672554428691",
                            Color = "silver",
                            SerialNumber = "05716449"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Incredible Frozen Soap",
                            UnitPrice = 62.989573244000545m,
                            Barcode = "5451787083994",
                            Color = "mint green",
                            SerialNumber = "76028793"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Sleek Concrete Car",
                            UnitPrice = 68.022158803894261m,
                            Barcode = "1336606305706",
                            Color = "gold",
                            SerialNumber = "02741505"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Sleek Soft Gloves",
                            UnitPrice = 26.632885415401693m,
                            Barcode = "3235097247039",
                            Color = "azure",
                            SerialNumber = "40486680"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Unbranded Steel Mouse",
                            UnitPrice = 29.111051356937263m,
                            Barcode = "0549132304339",
                            Color = "salmon",
                            SerialNumber = "70318463"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Intelligent Plastic Chips",
                            UnitPrice = 94.660811802214426m,
                            Barcode = "1299900317540",
                            Color = "yellow",
                            SerialNumber = "47104730"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Handmade Steel Car",
                            UnitPrice = 96.808484737206505m,
                            Barcode = "2744383653788",
                            Color = "orchid",
                            SerialNumber = "33394923"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Sleek Fresh Soap",
                            UnitPrice = 15.5539745127568m,
                            Barcode = "3584904113617",
                            Color = "green",
                            SerialNumber = "65924891"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Tasty Plastic Chicken",
                            UnitPrice = 99.863156755391149m,
                            Barcode = "3447711313185",
                            Color = "green",
                            SerialNumber = "09749665"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Handmade Concrete Gloves",
                            UnitPrice = 23.564051241410899m,
                            Barcode = "9055940087049",
                            Color = "azure",
                            SerialNumber = "56302295"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Practical Wooden Mouse",
                            UnitPrice = 27.069893874726229m,
                            Barcode = "1423673015772",
                            Color = "turquoise",
                            SerialNumber = "55473095"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Refined Plastic Salad",
                            UnitPrice = 2.3505767208293932m,
                            Barcode = "3574204880449",
                            Color = "black",
                            SerialNumber = "27414934"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Refined Rubber Hat",
                            UnitPrice = 46.702186948015444m,
                            Barcode = "7284196859908",
                            Color = "olive",
                            SerialNumber = "98801985"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Ergonomic Steel Table",
                            UnitPrice = 32.434595454220948m,
                            Barcode = "6878984701602",
                            Color = "orchid",
                            SerialNumber = "20694685"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Licensed Cotton Bike",
                            UnitPrice = 82.233044233281622m,
                            Barcode = "1288705782837",
                            Color = "plum",
                            SerialNumber = "18875294"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Intelligent Soft Bacon",
                            UnitPrice = 96.101854098076837m,
                            Barcode = "3804218161662",
                            Color = "blue",
                            SerialNumber = "95995922"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Intelligent Plastic Pizza",
                            UnitPrice = 92.111933321744203m,
                            Barcode = "7185444348482",
                            Color = "plum",
                            SerialNumber = "00464673"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Intelligent Concrete Fish",
                            UnitPrice = 18.70154335242766m,
                            Barcode = "2922588004615",
                            Color = "lavender",
                            SerialNumber = "32627213"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Small Wooden Sausages",
                            UnitPrice = 59.825480429374417m,
                            Barcode = "4555594538348",
                            Color = "turquoise",
                            SerialNumber = "11869481"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Fantastic Plastic Pants",
                            UnitPrice = 48.83688301632031m,
                            Barcode = "9519058007806",
                            Color = "yellow",
                            SerialNumber = "32510171"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Unbranded Concrete Car",
                            UnitPrice = 34.363174165768216m,
                            Barcode = "4526330124606",
                            Color = "olive",
                            SerialNumber = "74589241"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Incredible Soft Ball",
                            UnitPrice = 88.975532919622744m,
                            Barcode = "8652581744440",
                            Color = "olive",
                            SerialNumber = "32777680"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Handcrafted Granite Pants",
                            UnitPrice = 34.375876504171597m,
                            Barcode = "5856773625767",
                            Color = "sky blue",
                            SerialNumber = "77532855"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Small Wooden Towels",
                            UnitPrice = 72.155102361997159m,
                            Barcode = "4766949330764",
                            Color = "magenta",
                            SerialNumber = "34071816"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Practical Wooden Sausages",
                            UnitPrice = 76.241880128272726m,
                            Barcode = "1468095338207",
                            Color = "lavender",
                            SerialNumber = "17686433"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Small Fresh Chair",
                            UnitPrice = 49.623140918381095m,
                            Barcode = "8822082386450",
                            Color = "ivory",
                            SerialNumber = "71335339"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Gorgeous Frozen Soap",
                            UnitPrice = 47.577522247833016m,
                            Barcode = "1210819249913",
                            Color = "grey",
                            SerialNumber = "72355817"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Gorgeous Wooden Keyboard",
                            UnitPrice = 84.791028431985094m,
                            Barcode = "1926554828183",
                            Color = "turquoise",
                            SerialNumber = "72567210"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Intelligent Wooden Towels",
                            UnitPrice = 90.046351074262681m,
                            Barcode = "0884811906887",
                            Color = "teal",
                            SerialNumber = "92784192"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Intelligent Rubber Cheese",
                            UnitPrice = 7.7824600966565542m,
                            Barcode = "2570022030678",
                            Color = "grey",
                            SerialNumber = "60007179"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Fantastic Metal Fish",
                            UnitPrice = 85.742210986903954m,
                            Barcode = "4230160405124",
                            Color = "violet",
                            SerialNumber = "30873841"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Handcrafted Steel Mouse",
                            UnitPrice = 14.565336111730612m,
                            Barcode = "0910870673580",
                            Color = "violet",
                            SerialNumber = "91860163"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Refined Soft Chicken",
                            UnitPrice = 6.7856614057839223m,
                            Barcode = "3965287409021",
                            Color = "magenta",
                            SerialNumber = "59635543"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Practical Steel Salad",
                            UnitPrice = 95.601007785928006m,
                            Barcode = "9785305324785",
                            Color = "teal",
                            SerialNumber = "04385172"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Rustic Metal Keyboard",
                            UnitPrice = 8.5309176899171017m,
                            Barcode = "4363262204644",
                            Color = "green",
                            SerialNumber = "01093704"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Gorgeous Soft Ball",
                            UnitPrice = 60.190156379337544m,
                            Barcode = "1643290267099",
                            Color = "green",
                            SerialNumber = "42052487"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Refined Frozen Bacon",
                            UnitPrice = 30.371859864504982m,
                            Barcode = "0854607705161",
                            Color = "maroon",
                            SerialNumber = "19913384"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Rustic Steel Hat",
                            UnitPrice = 89.311637459467972m,
                            Barcode = "6488962170247",
                            Color = "blue",
                            SerialNumber = "36550395"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Ergonomic Cotton Table",
                            UnitPrice = 9.1722321725321134m,
                            Barcode = "4724152025723",
                            Color = "orange",
                            SerialNumber = "29843985"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Handcrafted Granite Bacon",
                            UnitPrice = 82.760241941437213m,
                            Barcode = "7228169305313",
                            Color = "indigo",
                            SerialNumber = "47028111"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Refined Plastic Gloves",
                            UnitPrice = 73.093517761255408m,
                            Barcode = "4451536994695",
                            Color = "green",
                            SerialNumber = "24865425"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Generic Metal Chips",
                            UnitPrice = 5.1139673609817277m,
                            Barcode = "9625399492369",
                            Color = "salmon",
                            SerialNumber = "08768322"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Ergonomic Wooden Chair",
                            UnitPrice = 99.178150739138074m,
                            Barcode = "3433054850180",
                            Color = "pink",
                            SerialNumber = "01594195"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Rustic Wooden Soap",
                            UnitPrice = 6.1797470111305534m,
                            Barcode = "6582394859180",
                            Color = "olive",
                            SerialNumber = "66338512"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Handcrafted Fresh Soap",
                            UnitPrice = 15.563634358608973m,
                            Barcode = "8359102186658",
                            Color = "indigo",
                            SerialNumber = "71465333"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Unbranded Metal Ball",
                            UnitPrice = 3.5589287972817811m,
                            Barcode = "8516059790400",
                            Color = "fuchsia",
                            SerialNumber = "35656005"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Tasty Fresh Tuna",
                            UnitPrice = 70.429127921084503m,
                            Barcode = "0543548107065",
                            Color = "magenta",
                            SerialNumber = "86136853"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Handcrafted Cotton Ball",
                            UnitPrice = 61.696042947329581m,
                            Barcode = "6848629984547",
                            Color = "green",
                            SerialNumber = "05251308"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Practical Steel Soap",
                            UnitPrice = 42.695001915420898m,
                            Barcode = "9730390624777",
                            Color = "blue",
                            SerialNumber = "90478178"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Ergonomic Metal Ball",
                            UnitPrice = 62.112854699656804m,
                            Barcode = "6953365623992",
                            Color = "yellow",
                            SerialNumber = "98694815"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Licensed Granite Hat",
                            UnitPrice = 63.481965975129052m,
                            Barcode = "8273220242334",
                            Color = "purple",
                            SerialNumber = "46368157"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Small Rubber Salad",
                            UnitPrice = 69.072966820128754m,
                            Barcode = "5892463143517",
                            Color = "lavender",
                            SerialNumber = "82303648"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Sleek Concrete Shoes",
                            UnitPrice = 3.9370501329829264m,
                            Barcode = "5576991238739",
                            Color = "gold",
                            SerialNumber = "28889298"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Ergonomic Concrete Cheese",
                            UnitPrice = 3.004265905825546m,
                            Barcode = "7523014231787",
                            Color = "salmon",
                            SerialNumber = "86252270"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Sleek Frozen Cheese",
                            UnitPrice = 11.633288156070382m,
                            Barcode = "8672347271942",
                            Color = "sky blue",
                            SerialNumber = "67213405"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Ergonomic Frozen Sausages",
                            UnitPrice = 68.509653729158278m,
                            Barcode = "9378470777533",
                            Color = "black",
                            SerialNumber = "42994404"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Handmade Soft Sausages",
                            UnitPrice = 85.249283305951126m,
                            Barcode = "0660964874293",
                            Color = "salmon",
                            SerialNumber = "79801164"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Intelligent Fresh Fish",
                            UnitPrice = 92.142368297158915m,
                            Barcode = "5176825141770",
                            Color = "purple",
                            SerialNumber = "00713665"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Unbranded Frozen Mouse",
                            UnitPrice = 52.895632389884272m,
                            Barcode = "5055103195486",
                            Color = "tan",
                            SerialNumber = "97949152"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Rustic Steel Chips",
                            UnitPrice = 54.538647702680305m,
                            Barcode = "3555282592080",
                            Color = "yellow",
                            SerialNumber = "79038683"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Awesome Frozen Mouse",
                            UnitPrice = 75.13047673559308m,
                            Barcode = "6197463504269",
                            Color = "salmon",
                            SerialNumber = "58913895"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Handcrafted Wooden Cheese",
                            UnitPrice = 28.753130646773191m,
                            Barcode = "1175145439813",
                            Color = "lavender",
                            SerialNumber = "84128577"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Handmade Cotton Bacon",
                            UnitPrice = 61.797196224237385m,
                            Barcode = "6726948530624",
                            Color = "silver",
                            SerialNumber = "98369720"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Small Fresh Ball",
                            UnitPrice = 81.677713299951394m,
                            Barcode = "7791442637833",
                            Color = "cyan",
                            SerialNumber = "28490371"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Handmade Fresh Ball",
                            UnitPrice = 23.879099208339649m,
                            Barcode = "1039119843924",
                            Color = "lavender",
                            SerialNumber = "47088993"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Small Frozen Table",
                            UnitPrice = 88.701367538748898m,
                            Barcode = "3356041949936",
                            Color = "green",
                            SerialNumber = "12517084"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Unbranded Concrete Table",
                            UnitPrice = 51.518776604681638m,
                            Barcode = "2807809263685",
                            Color = "orange",
                            SerialNumber = "63701074"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Licensed Soft Cheese",
                            UnitPrice = 78.950846584956565m,
                            Barcode = "4840051082428",
                            Color = "salmon",
                            SerialNumber = "43030767"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Generic Metal Shoes",
                            UnitPrice = 39.398328489809431m,
                            Barcode = "2878495414309",
                            Color = "turquoise",
                            SerialNumber = "59101505"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Unbranded Granite Soap",
                            UnitPrice = 1.22395353541893541m,
                            Barcode = "9440199730721",
                            Color = "indigo",
                            SerialNumber = "82697907"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Ergonomic Frozen Bacon",
                            UnitPrice = 58.507351983574867m,
                            Barcode = "6569615729804",
                            Color = "purple",
                            SerialNumber = "44314576"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Rustic Fresh Bike",
                            UnitPrice = 91.54280244398059m,
                            Barcode = "9069457053459",
                            Color = "cyan",
                            SerialNumber = "39124098"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Practical Rubber Table",
                            UnitPrice = 16.822917632210491m,
                            Barcode = "5955229737051",
                            Color = "orange",
                            SerialNumber = "45262845"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Small Fresh Bacon",
                            UnitPrice = 60.961899272614075m,
                            Barcode = "4511934463459",
                            Color = "tan",
                            SerialNumber = "01733716"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Tasty Granite Cheese",
                            UnitPrice = 12.49182868678669m,
                            Barcode = "7265122710173",
                            Color = "cyan",
                            SerialNumber = "08702692"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Rustic Soft Tuna",
                            UnitPrice = 4.8959912121742909m,
                            Barcode = "1083615972367",
                            Color = "blue",
                            SerialNumber = "68230630"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Small Frozen Ball",
                            UnitPrice = 85.373028393542911m,
                            Barcode = "9133667066407",
                            Color = "sky blue",
                            SerialNumber = "49094206"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Sleek Wooden Table",
                            UnitPrice = 1.77610685572778149m,
                            Barcode = "3505350182453",
                            Color = "maroon",
                            SerialNumber = "82215309"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Practical Concrete Sausages",
                            UnitPrice = 19.831775282431309m,
                            Barcode = "5458940769009",
                            Color = "purple",
                            SerialNumber = "62606226"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Sleek Granite Car",
                            UnitPrice = 94.959968062099051m,
                            Barcode = "9931149068990",
                            Color = "white",
                            SerialNumber = "01132687"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Intelligent Concrete Hat",
                            UnitPrice = 73.142123881327984m,
                            Barcode = "6931076033903",
                            Color = "pink",
                            SerialNumber = "19620947"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Gorgeous Metal Car",
                            UnitPrice = 69.934993606496116m,
                            Barcode = "0898610749415",
                            Color = "violet",
                            SerialNumber = "07082863"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Intelligent Wooden Ball",
                            UnitPrice = 12.763716059161198m,
                            Barcode = "0692770999112",
                            Color = "orange",
                            SerialNumber = "77422262"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Practical Granite Ball",
                            UnitPrice = 8.0424383352708286m,
                            Barcode = "8644032956809",
                            Color = "black",
                            SerialNumber = "17969420"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Generic Frozen Computer",
                            UnitPrice = 11.502032703022531m,
                            Barcode = "3349418536419",
                            Color = "tan",
                            SerialNumber = "26857152"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Unbranded Cotton Chair",
                            UnitPrice = 51.862512293207659m,
                            Barcode = "2019116959070",
                            Color = "tan",
                            SerialNumber = "92448360"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Incredible Fresh Gloves",
                            UnitPrice = 31.504614826992427m,
                            Barcode = "6734395939747",
                            Color = "pink",
                            SerialNumber = "98310555"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Awesome Wooden Tuna",
                            UnitPrice = 1.84357571967112609m,
                            Barcode = "7125751368346",
                            Color = "tan",
                            SerialNumber = "81553037"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Sleek Frozen Table",
                            UnitPrice = 13.832369520250852m,
                            Barcode = "9448207408716",
                            Color = "lavender",
                            SerialNumber = "60287373"
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Service", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<TimeSpan?>("Duration");

                    b.HasDiscriminator().HasValue("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "override",
                            UnitPrice = 314.973846736817600m,
                            Duration = new TimeSpan(12974463562)
                        },
                        new
                        {
                            Id = 2,
                            Name = "hack",
                            UnitPrice = 280.737470733345200m,
                            Duration = new TimeSpan(19881621467)
                        },
                        new
                        {
                            Id = 3,
                            Name = "quantify",
                            UnitPrice = 245.986115255386800m,
                            Duration = new TimeSpan(64093561623)
                        },
                        new
                        {
                            Id = 4,
                            Name = "bypass",
                            UnitPrice = 263.413639815251200m,
                            Duration = new TimeSpan(7507305123)
                        },
                        new
                        {
                            Id = 5,
                            Name = "hack",
                            UnitPrice = 161.374972602992800m,
                            Duration = new TimeSpan(29070082428)
                        },
                        new
                        {
                            Id = 6,
                            Name = "index",
                            UnitPrice = 373.905660898380800m,
                            Duration = new TimeSpan(2952306726)
                        },
                        new
                        {
                            Id = 7,
                            Name = "quantify",
                            UnitPrice = 484.614654809522800m,
                            Duration = new TimeSpan(71798495393)
                        },
                        new
                        {
                            Id = 8,
                            Name = "back up",
                            UnitPrice = 297.383485453847600m,
                            Duration = new TimeSpan(20886010105)
                        },
                        new
                        {
                            Id = 9,
                            Name = "connect",
                            UnitPrice = 175.901584921358800m,
                            Duration = new TimeSpan(30035227566)
                        },
                        new
                        {
                            Id = 10,
                            Name = "quantify",
                            UnitPrice = 469.249598667607600m,
                            Duration = new TimeSpan(8299590908)
                        },
                        new
                        {
                            Id = 11,
                            Name = "reboot",
                            UnitPrice = 301.921812166423600m,
                            Duration = new TimeSpan(11786813160)
                        },
                        new
                        {
                            Id = 12,
                            Name = "compress",
                            UnitPrice = 343.832688892182400m,
                            Duration = new TimeSpan(47677056413)
                        },
                        new
                        {
                            Id = 13,
                            Name = "copy",
                            UnitPrice = 388.657134533234400m,
                            Duration = new TimeSpan(37530655230)
                        },
                        new
                        {
                            Id = 14,
                            Name = "copy",
                            UnitPrice = 325.130840123226400m,
                            Duration = new TimeSpan(65672042769)
                        },
                        new
                        {
                            Id = 15,
                            Name = "index",
                            UnitPrice = 291.300380877824800m,
                            Duration = new TimeSpan(51543342123)
                        },
                        new
                        {
                            Id = 16,
                            Name = "bypass",
                            UnitPrice = 213.981477969317600m,
                            Duration = new TimeSpan(1101456844)
                        },
                        new
                        {
                            Id = 17,
                            Name = "transmit",
                            UnitPrice = 291.52436824120800m,
                            Duration = new TimeSpan(43737078989)
                        },
                        new
                        {
                            Id = 18,
                            Name = "parse",
                            UnitPrice = 103.66286859086848400m,
                            Duration = new TimeSpan(60106726477)
                        },
                        new
                        {
                            Id = 19,
                            Name = "generate",
                            UnitPrice = 168.41040536221600m,
                            Duration = new TimeSpan(3166265031)
                        },
                        new
                        {
                            Id = 20,
                            Name = "reboot",
                            UnitPrice = 355.363211899699200m,
                            Duration = new TimeSpan(18870459446)
                        },
                        new
                        {
                            Id = 21,
                            Name = "program",
                            UnitPrice = 496.572066469384400m,
                            Duration = new TimeSpan(31812572986)
                        },
                        new
                        {
                            Id = 22,
                            Name = "input",
                            UnitPrice = 153.340038868291200m,
                            Duration = new TimeSpan(65068528977)
                        },
                        new
                        {
                            Id = 23,
                            Name = "reboot",
                            UnitPrice = 450.411657407140400m,
                            Duration = new TimeSpan(39157611068)
                        },
                        new
                        {
                            Id = 24,
                            Name = "input",
                            UnitPrice = 134.6054280337902800m,
                            Duration = new TimeSpan(69344734746)
                        },
                        new
                        {
                            Id = 25,
                            Name = "generate",
                            UnitPrice = 204.05283090847200m,
                            Duration = new TimeSpan(28707086644)
                        },
                        new
                        {
                            Id = 26,
                            Name = "bypass",
                            UnitPrice = 350.947461207838400m,
                            Duration = new TimeSpan(1094958824)
                        },
                        new
                        {
                            Id = 27,
                            Name = "quantify",
                            UnitPrice = 254.398926791920800m,
                            Duration = new TimeSpan(65145619251)
                        },
                        new
                        {
                            Id = 28,
                            Name = "index",
                            UnitPrice = 415.897297820028400m,
                            Duration = new TimeSpan(31990541477)
                        },
                        new
                        {
                            Id = 29,
                            Name = "generate",
                            UnitPrice = 490.452464851761600m,
                            Duration = new TimeSpan(35686609844)
                        },
                        new
                        {
                            Id = 30,
                            Name = "copy",
                            UnitPrice = 391.88487617852400m,
                            Duration = new TimeSpan(31576011035)
                        },
                        new
                        {
                            Id = 31,
                            Name = "calculate",
                            UnitPrice = 266.880118924602800m,
                            Duration = new TimeSpan(5992906074)
                        },
                        new
                        {
                            Id = 32,
                            Name = "compress",
                            UnitPrice = 289.001057385002000m,
                            Duration = new TimeSpan(41140579258)
                        },
                        new
                        {
                            Id = 33,
                            Name = "connect",
                            UnitPrice = 356.44958739003600m,
                            Duration = new TimeSpan(24832861562)
                        },
                        new
                        {
                            Id = 34,
                            Name = "transmit",
                            UnitPrice = 160.341452835286800m,
                            Duration = new TimeSpan(29442567701)
                        },
                        new
                        {
                            Id = 35,
                            Name = "connect",
                            UnitPrice = 131.490684501589600m,
                            Duration = new TimeSpan(28245409237)
                        },
                        new
                        {
                            Id = 36,
                            Name = "calculate",
                            UnitPrice = 275.674484379438000m,
                            Duration = new TimeSpan(53929806783)
                        },
                        new
                        {
                            Id = 37,
                            Name = "index",
                            UnitPrice = 269.5945714458800m,
                            Duration = new TimeSpan(39143329948)
                        },
                        new
                        {
                            Id = 38,
                            Name = "back up",
                            UnitPrice = 226.365474856628800m,
                            Duration = new TimeSpan(18173571319)
                        },
                        new
                        {
                            Id = 39,
                            Name = "navigate",
                            UnitPrice = 282.847906547993600m,
                            Duration = new TimeSpan(14521458357)
                        },
                        new
                        {
                            Id = 40,
                            Name = "parse",
                            UnitPrice = 206.841437754613200m,
                            Duration = new TimeSpan(11319763323)
                        },
                        new
                        {
                            Id = 41,
                            Name = "index",
                            UnitPrice = 344.668918216912400m,
                            Duration = new TimeSpan(10534820621)
                        },
                        new
                        {
                            Id = 42,
                            Name = "bypass",
                            UnitPrice = 149.345747963220800m,
                            Duration = new TimeSpan(48190555640)
                        },
                        new
                        {
                            Id = 43,
                            Name = "program",
                            UnitPrice = 204.230309512573600m,
                            Duration = new TimeSpan(56709319234)
                        },
                        new
                        {
                            Id = 44,
                            Name = "transmit",
                            UnitPrice = 345.927682447213600m,
                            Duration = new TimeSpan(71009617287)
                        },
                        new
                        {
                            Id = 45,
                            Name = "synthesize",
                            UnitPrice = 404.821415760005600m,
                            Duration = new TimeSpan(16930345312)
                        },
                        new
                        {
                            Id = 46,
                            Name = "connect",
                            UnitPrice = 472.166249701830800m,
                            Duration = new TimeSpan(51193190397)
                        },
                        new
                        {
                            Id = 47,
                            Name = "back up",
                            UnitPrice = 445.389820423624400m,
                            Duration = new TimeSpan(38660036485)
                        },
                        new
                        {
                            Id = 48,
                            Name = "input",
                            UnitPrice = 457.113593610522000m,
                            Duration = new TimeSpan(22012254852)
                        },
                        new
                        {
                            Id = 49,
                            Name = "reboot",
                            UnitPrice = 335.774917637824400m,
                            Duration = new TimeSpan(7292635932)
                        },
                        new
                        {
                            Id = 50,
                            Name = "transmit",
                            UnitPrice = 460.751975495718400m,
                            Duration = new TimeSpan(1107567151)
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.OwnsOne("Altkom.Shop.Models.Address", "InvoiceAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("InvoiceAddresses");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("InvoiceAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Altkom.Shop.Models.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("ShippingAddresses");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("ShippingAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Altkom.Shop.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
