// <auto-generated />
using System;
using Altkom.Shop.DbRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Altkom.Shop.DbRepositories.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20190913005222_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime?>("DeliveredDate");

                    b.Property<string>("Number");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<short>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Product", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<string>("Barcode");

                    b.Property<string>("Color")
                        .HasMaxLength(20);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasDiscriminator().HasValue("Product");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Name = "Awesome Granite Hat",
                            UnitPrice = 74.07055433423746m,
                            Barcode = "1751935716465",
                            Color = "lime",
                            SerialNumber = "97995623"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ergonomic Rubber Fish",
                            UnitPrice = 13.550668418663848m,
                            Barcode = "7357642687902",
                            Color = "teal",
                            SerialNumber = "69207587"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Handmade Fresh Gloves",
                            UnitPrice = 12.938523177028888m,
                            Barcode = "9919276503454",
                            Color = "olive",
                            SerialNumber = "87074772"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Refined Fresh Gloves",
                            UnitPrice = 25.859236867101505m,
                            Barcode = "4195764808866",
                            Color = "plum",
                            SerialNumber = "23401303"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Awesome Rubber Keyboard",
                            UnitPrice = 1.55752176584560456m,
                            Barcode = "4169028065418",
                            Color = "blue",
                            SerialNumber = "81838554"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Refined Granite Towels",
                            UnitPrice = 61.832900529183871m,
                            Barcode = "3794700808161",
                            Color = "yellow",
                            SerialNumber = "94780895"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Unbranded Plastic Mouse",
                            UnitPrice = 97.639821566473636m,
                            Barcode = "4630012955638",
                            Color = "red",
                            SerialNumber = "23265608"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Small Concrete Shoes",
                            UnitPrice = 35.230096775679904m,
                            Barcode = "7790592059915",
                            Color = "maroon",
                            SerialNumber = "70786101"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Refined Cotton Soap",
                            UnitPrice = 26.501203671331168m,
                            Barcode = "5302220229236",
                            Color = "olive",
                            SerialNumber = "12463688"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Fantastic Wooden Salad",
                            UnitPrice = 75.743980650205174m,
                            Barcode = "9238115213416",
                            Color = "tan",
                            SerialNumber = "89839782"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Handmade Plastic Chicken",
                            UnitPrice = 85.639617577493011m,
                            Barcode = "7492632445398",
                            Color = "grey",
                            SerialNumber = "81013920"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Licensed Concrete Fish",
                            UnitPrice = 28.488877696212823m,
                            Barcode = "7436217559063",
                            Color = "maroon",
                            SerialNumber = "13670078"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Generic Fresh Shoes",
                            UnitPrice = 87.832370592203203m,
                            Barcode = "6737085575416",
                            Color = "ivory",
                            SerialNumber = "06128746"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ergonomic Cotton Chips",
                            UnitPrice = 54.996291053945317m,
                            Barcode = "2587447905948",
                            Color = "blue",
                            SerialNumber = "89574591"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Licensed Rubber Fish",
                            UnitPrice = 50.291526794103649m,
                            Barcode = "8548456382452",
                            Color = "pink",
                            SerialNumber = "98027507"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Handmade Metal Table",
                            UnitPrice = 54.56246965823809m,
                            Barcode = "2645442784897",
                            Color = "azure",
                            SerialNumber = "09448667"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Practical Steel Fish",
                            UnitPrice = 50.526603358111594m,
                            Barcode = "5672425105575",
                            Color = "plum",
                            SerialNumber = "11849773"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Unbranded Wooden Bike",
                            UnitPrice = 53.063279598049489m,
                            Barcode = "1661094298972",
                            Color = "gold",
                            SerialNumber = "60258687"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Practical Metal Pants",
                            UnitPrice = 25.513481609296768m,
                            Barcode = "7257226349182",
                            Color = "olive",
                            SerialNumber = "54110281"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Intelligent Wooden Fish",
                            UnitPrice = 73.295679236899888m,
                            Barcode = "4162273429387",
                            Color = "lavender",
                            SerialNumber = "37962623"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Unbranded Cotton Chair",
                            UnitPrice = 61.896160097744356m,
                            Barcode = "5741804556212",
                            Color = "maroon",
                            SerialNumber = "64075655"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Rustic Plastic Cheese",
                            UnitPrice = 75.919414734430354m,
                            Barcode = "2105890012756",
                            Color = "pink",
                            SerialNumber = "21624728"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Sleek Soft Car",
                            UnitPrice = 43.654262516952229m,
                            Barcode = "5513932191869",
                            Color = "indigo",
                            SerialNumber = "09755208"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Handcrafted Granite Shoes",
                            UnitPrice = 12.353543557856929m,
                            Barcode = "9313008512033",
                            Color = "grey",
                            SerialNumber = "87179569"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Incredible Steel Keyboard",
                            UnitPrice = 80.132089973023252m,
                            Barcode = "0712661007358",
                            Color = "salmon",
                            SerialNumber = "28182351"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Unbranded Cotton Chicken",
                            UnitPrice = 7.4827726671857644m,
                            Barcode = "1341830915324",
                            Color = "cyan",
                            SerialNumber = "86841924"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Fantastic Granite Table",
                            UnitPrice = 69.331051205439022m,
                            Barcode = "4789436612136",
                            Color = "green",
                            SerialNumber = "19267449"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Awesome Fresh Chair",
                            UnitPrice = 56.36960535513682m,
                            Barcode = "5069165594606",
                            Color = "olive",
                            SerialNumber = "51489618"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Sleek Granite Pants",
                            UnitPrice = 71.363331212831371m,
                            Barcode = "6539175571441",
                            Color = "yellow",
                            SerialNumber = "66557531"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Incredible Concrete Keyboard",
                            UnitPrice = 37.890895205033452m,
                            Barcode = "9678741065353",
                            Color = "plum",
                            SerialNumber = "25419122"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Handmade Frozen Computer",
                            UnitPrice = 15.411469485336715m,
                            Barcode = "1679168447041",
                            Color = "white",
                            SerialNumber = "96829370"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Fantastic Steel Ball",
                            UnitPrice = 49.664956162993291m,
                            Barcode = "0281978955701",
                            Color = "black",
                            SerialNumber = "72907801"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Awesome Frozen Mouse",
                            UnitPrice = 45.519909342061681m,
                            Barcode = "2033298135985",
                            Color = "white",
                            SerialNumber = "86468091"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Unbranded Soft Towels",
                            UnitPrice = 21.421192532135725m,
                            Barcode = "4744977005892",
                            Color = "indigo",
                            SerialNumber = "35756668"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Gorgeous Steel Mouse",
                            UnitPrice = 28.913186398760047m,
                            Barcode = "4464973446948",
                            Color = "green",
                            SerialNumber = "54167889"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Licensed Granite Ball",
                            UnitPrice = 78.455119222614529m,
                            Barcode = "3473034353058",
                            Color = "pink",
                            SerialNumber = "12022359"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Awesome Concrete Chips",
                            UnitPrice = 17.162504877970792m,
                            Barcode = "4044292912159",
                            Color = "white",
                            SerialNumber = "99401696"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Fantastic Metal Table",
                            UnitPrice = 86.275868937967279m,
                            Barcode = "8503947045995",
                            Color = "sky blue",
                            SerialNumber = "90160035"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Ergonomic Granite Pants",
                            UnitPrice = 37.867683481363405m,
                            Barcode = "9469288768667",
                            Color = "white",
                            SerialNumber = "89965009"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Ergonomic Cotton Keyboard",
                            UnitPrice = 5.1735756342176182m,
                            Barcode = "4303354227359",
                            Color = "green",
                            SerialNumber = "87867237"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Practical Granite Cheese",
                            UnitPrice = 9.9729783912063493m,
                            Barcode = "1639491536492",
                            Color = "mint green",
                            SerialNumber = "75304331"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Awesome Granite Pizza",
                            UnitPrice = 21.604243012892209m,
                            Barcode = "2468005959262",
                            Color = "lime",
                            SerialNumber = "24825719"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Incredible Fresh Pizza",
                            UnitPrice = 85.538995885075501m,
                            Barcode = "8360166686794",
                            Color = "white",
                            SerialNumber = "33520544"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Incredible Metal Cheese",
                            UnitPrice = 66.176788485691333m,
                            Barcode = "5057264454075",
                            Color = "lavender",
                            SerialNumber = "44882570"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Handmade Soft Sausages",
                            UnitPrice = 93.222306737779834m,
                            Barcode = "2918409156502",
                            Color = "white",
                            SerialNumber = "18321241"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Incredible Fresh Cheese",
                            UnitPrice = 83.847746206376569m,
                            Barcode = "7557912712536",
                            Color = "sky blue",
                            SerialNumber = "46054913"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Unbranded Soft Fish",
                            UnitPrice = 90.275399356743028m,
                            Barcode = "2544409316082",
                            Color = "maroon",
                            SerialNumber = "42144892"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Fantastic Frozen Cheese",
                            UnitPrice = 78.22243462746142m,
                            Barcode = "2844695981439",
                            Color = "plum",
                            SerialNumber = "67313112"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Sleek Wooden Keyboard",
                            UnitPrice = 24.428779422970834m,
                            Barcode = "7740880278252",
                            Color = "black",
                            SerialNumber = "54720107"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Handmade Soft Cheese",
                            UnitPrice = 77.301831665123713m,
                            Barcode = "5752800061792",
                            Color = "olive",
                            SerialNumber = "54101258"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Sleek Metal Towels",
                            UnitPrice = 37.433492359907104m,
                            Barcode = "4873195997501",
                            Color = "fuchsia",
                            SerialNumber = "27478196"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Licensed Soft Cheese",
                            UnitPrice = 75.872860039059445m,
                            Barcode = "0004201826896",
                            Color = "salmon",
                            SerialNumber = "26976808"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Unbranded Steel Cheese",
                            UnitPrice = 58.861683818447212m,
                            Barcode = "8893720611302",
                            Color = "maroon",
                            SerialNumber = "81696789"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Unbranded Granite Shoes",
                            UnitPrice = 17.131864847676787m,
                            Barcode = "1279706926634",
                            Color = "yellow",
                            SerialNumber = "07005183"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Fantastic Frozen Pizza",
                            UnitPrice = 20.126595655049509m,
                            Barcode = "1111214338250",
                            Color = "sky blue",
                            SerialNumber = "41914373"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Sleek Plastic Pizza",
                            UnitPrice = 22.54130992737658m,
                            Barcode = "7807627232851",
                            Color = "fuchsia",
                            SerialNumber = "84711298"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Sleek Granite Towels",
                            UnitPrice = 25.503250947456457m,
                            Barcode = "2669160823447",
                            Color = "violet",
                            SerialNumber = "17700016"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Incredible Plastic Ball",
                            UnitPrice = 55.364615763707359m,
                            Barcode = "6602363125594",
                            Color = "silver",
                            SerialNumber = "67061037"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Small Plastic Sausages",
                            UnitPrice = 59.647294516045312m,
                            Barcode = "5915331846348",
                            Color = "turquoise",
                            SerialNumber = "67559213"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Intelligent Soft Shoes",
                            UnitPrice = 93.621343901670199m,
                            Barcode = "9402079275739",
                            Color = "orange",
                            SerialNumber = "58894651"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Fantastic Rubber Chair",
                            UnitPrice = 12.123817091399683m,
                            Barcode = "5757132748588",
                            Color = "turquoise",
                            SerialNumber = "28877073"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Tasty Wooden Computer",
                            UnitPrice = 68.445065867828671m,
                            Barcode = "4215259345727",
                            Color = "mint green",
                            SerialNumber = "11133094"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Intelligent Frozen Chicken",
                            UnitPrice = 67.340768954409631m,
                            Barcode = "8723895364393",
                            Color = "plum",
                            SerialNumber = "27599242"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Small Rubber Soap",
                            UnitPrice = 74.211700826981926m,
                            Barcode = "9489149455642",
                            Color = "sky blue",
                            SerialNumber = "36450466"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Licensed Concrete Keyboard",
                            UnitPrice = 65.784707882341282m,
                            Barcode = "5079505226333",
                            Color = "salmon",
                            SerialNumber = "15124937"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Small Steel Soap",
                            UnitPrice = 64.358644596468067m,
                            Barcode = "8856987732319",
                            Color = "orange",
                            SerialNumber = "60850423"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Gorgeous Steel Table",
                            UnitPrice = 87.393190478157838m,
                            Barcode = "2328845444161",
                            Color = "turquoise",
                            SerialNumber = "49239508"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Intelligent Steel Soap",
                            UnitPrice = 15.774877810745866m,
                            Barcode = "1865890741469",
                            Color = "violet",
                            SerialNumber = "58986875"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Unbranded Wooden Computer",
                            UnitPrice = 32.172936208161022m,
                            Barcode = "1866952178797",
                            Color = "blue",
                            SerialNumber = "89644324"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Sleek Metal Cheese",
                            UnitPrice = 71.917159501424566m,
                            Barcode = "6213245975499",
                            Color = "blue",
                            SerialNumber = "23798281"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Ergonomic Steel Chair",
                            UnitPrice = 27.035139838715623m,
                            Barcode = "2365976406071",
                            Color = "lime",
                            SerialNumber = "39923813"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Sleek Metal Keyboard",
                            UnitPrice = 68.087476343422909m,
                            Barcode = "6342709624090",
                            Color = "yellow",
                            SerialNumber = "70999983"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Incredible Steel Towels",
                            UnitPrice = 90.346899844867654m,
                            Barcode = "3642872515861",
                            Color = "azure",
                            SerialNumber = "33706443"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Refined Steel Shoes",
                            UnitPrice = 20.051243426767717m,
                            Barcode = "8235847675919",
                            Color = "black",
                            SerialNumber = "67752577"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Rustic Plastic Tuna",
                            UnitPrice = 79.975645501155238m,
                            Barcode = "2808560311462",
                            Color = "plum",
                            SerialNumber = "46677297"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Practical Rubber Pants",
                            UnitPrice = 51.243631496673274m,
                            Barcode = "6962230556303",
                            Color = "azure",
                            SerialNumber = "49014600"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Gorgeous Wooden Car",
                            UnitPrice = 75.188953057950775m,
                            Barcode = "8049481641151",
                            Color = "orchid",
                            SerialNumber = "98080908"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Gorgeous Metal Gloves",
                            UnitPrice = 27.723544750233892m,
                            Barcode = "1737586590425",
                            Color = "fuchsia",
                            SerialNumber = "81075751"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Handmade Rubber Computer",
                            UnitPrice = 97.450974920043271m,
                            Barcode = "5243133275869",
                            Color = "orchid",
                            SerialNumber = "44165666"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Fantastic Soft Salad",
                            UnitPrice = 34.91599064130145m,
                            Barcode = "8225101567128",
                            Color = "azure",
                            SerialNumber = "42466154"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Incredible Granite Ball",
                            UnitPrice = 76.9260619603684m,
                            Barcode = "5970912835586",
                            Color = "blue",
                            SerialNumber = "07174292"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Intelligent Fresh Bike",
                            UnitPrice = 89.285753568301795m,
                            Barcode = "2931255301018",
                            Color = "teal",
                            SerialNumber = "20654399"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Handmade Rubber Towels",
                            UnitPrice = 89.926929196308775m,
                            Barcode = "0891558675891",
                            Color = "cyan",
                            SerialNumber = "80579182"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Licensed Frozen Table",
                            UnitPrice = 72.57388961155609m,
                            Barcode = "5338934644041",
                            Color = "grey",
                            SerialNumber = "64852348"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Intelligent Metal Fish",
                            UnitPrice = 39.032076410964163m,
                            Barcode = "8295860135517",
                            Color = "grey",
                            SerialNumber = "10730249"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Tasty Steel Car",
                            UnitPrice = 14.127883889306329m,
                            Barcode = "3364471869977",
                            Color = "turquoise",
                            SerialNumber = "38873904"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Unbranded Metal Gloves",
                            UnitPrice = 26.017401854515708m,
                            Barcode = "5169233714254",
                            Color = "black",
                            SerialNumber = "06763657"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Small Steel Chair",
                            UnitPrice = 88.041687459704362m,
                            Barcode = "4700995693831",
                            Color = "mint green",
                            SerialNumber = "01625257"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Generic Plastic Fish",
                            UnitPrice = 73.766415720231046m,
                            Barcode = "2472102514545",
                            Color = "olive",
                            SerialNumber = "33819655"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Refined Cotton Soap",
                            UnitPrice = 60.187569866509942m,
                            Barcode = "0378415003856",
                            Color = "mint green",
                            SerialNumber = "12590223"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Generic Wooden Sausages",
                            UnitPrice = 94.61064458201203m,
                            Barcode = "4399898885285",
                            Color = "mint green",
                            SerialNumber = "34098547"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Awesome Plastic Chair",
                            UnitPrice = 58.967612596679302m,
                            Barcode = "1565195835305",
                            Color = "olive",
                            SerialNumber = "16205963"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Small Metal Towels",
                            UnitPrice = 83.481115780994788m,
                            Barcode = "2270696132820",
                            Color = "orchid",
                            SerialNumber = "33789347"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Ergonomic Steel Cheese",
                            UnitPrice = 92.128398334201558m,
                            Barcode = "2445646400384",
                            Color = "white",
                            SerialNumber = "25138269"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Licensed Steel Fish",
                            UnitPrice = 27.415747603129456m,
                            Barcode = "2856275144820",
                            Color = "teal",
                            SerialNumber = "50596423"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Tasty Fresh Soap",
                            UnitPrice = 79.48286105435479m,
                            Barcode = "2098384172374",
                            Color = "tan",
                            SerialNumber = "89124130"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Generic Frozen Pizza",
                            UnitPrice = 36.75806210225359m,
                            Barcode = "7623842320421",
                            Color = "gold",
                            SerialNumber = "77860743"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Handcrafted Soft Keyboard",
                            UnitPrice = 73.901588606602327m,
                            Barcode = "2978488221164",
                            Color = "lime",
                            SerialNumber = "61239050"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Sleek Frozen Shoes",
                            UnitPrice = 66.572182191336634m,
                            Barcode = "2779441955092",
                            Color = "ivory",
                            SerialNumber = "63932102"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Generic Concrete Chair",
                            UnitPrice = 9.7783239156838192m,
                            Barcode = "4136142340561",
                            Color = "azure",
                            SerialNumber = "09879119"
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Service", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<TimeSpan?>("Duration");

                    b.HasDiscriminator().HasValue("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "reboot",
                            UnitPrice = 271.219475647071200m,
                            Duration = new TimeSpan(48783663601)
                        },
                        new
                        {
                            Id = 2,
                            Name = "hack",
                            UnitPrice = 351.281255973168400m,
                            Duration = new TimeSpan(67651735110)
                        },
                        new
                        {
                            Id = 3,
                            Name = "back up",
                            UnitPrice = 393.596391330285200m,
                            Duration = new TimeSpan(27375611065)
                        },
                        new
                        {
                            Id = 4,
                            Name = "override",
                            UnitPrice = 286.597106692659200m,
                            Duration = new TimeSpan(52165475408)
                        },
                        new
                        {
                            Id = 5,
                            Name = "reboot",
                            UnitPrice = 132.3942268418121200m,
                            Duration = new TimeSpan(384231035)
                        },
                        new
                        {
                            Id = 6,
                            Name = "connect",
                            UnitPrice = 424.573352525277600m,
                            Duration = new TimeSpan(71575524162)
                        },
                        new
                        {
                            Id = 7,
                            Name = "generate",
                            UnitPrice = 493.04346348766400m,
                            Duration = new TimeSpan(56221428566)
                        },
                        new
                        {
                            Id = 8,
                            Name = "parse",
                            UnitPrice = 267.333056483107200m,
                            Duration = new TimeSpan(58485270039)
                        },
                        new
                        {
                            Id = 9,
                            Name = "compress",
                            UnitPrice = 228.097397521183600m,
                            Duration = new TimeSpan(46895253404)
                        },
                        new
                        {
                            Id = 10,
                            Name = "generate",
                            UnitPrice = 249.133016424781200m,
                            Duration = new TimeSpan(64802867305)
                        },
                        new
                        {
                            Id = 11,
                            Name = "navigate",
                            UnitPrice = 276.411061257315200m,
                            Duration = new TimeSpan(64978325181)
                        },
                        new
                        {
                            Id = 12,
                            Name = "input",
                            UnitPrice = 255.426374522702000m,
                            Duration = new TimeSpan(50519316697)
                        },
                        new
                        {
                            Id = 13,
                            Name = "override",
                            UnitPrice = 309.451721706172400m,
                            Duration = new TimeSpan(27193155406)
                        },
                        new
                        {
                            Id = 14,
                            Name = "transmit",
                            UnitPrice = 432.192629544154000m,
                            Duration = new TimeSpan(34194425219)
                        },
                        new
                        {
                            Id = 15,
                            Name = "back up",
                            UnitPrice = 441.384829367224400m,
                            Duration = new TimeSpan(61346845816)
                        },
                        new
                        {
                            Id = 16,
                            Name = "hack",
                            UnitPrice = 161.36335826542400m,
                            Duration = new TimeSpan(6961476594)
                        },
                        new
                        {
                            Id = 17,
                            Name = "program",
                            UnitPrice = 351.51323352545200m,
                            Duration = new TimeSpan(32299035244)
                        },
                        new
                        {
                            Id = 18,
                            Name = "program",
                            UnitPrice = 120.6132235101485600m,
                            Duration = new TimeSpan(45069190486)
                        },
                        new
                        {
                            Id = 19,
                            Name = "reboot",
                            UnitPrice = 470.05739992952800m,
                            Duration = new TimeSpan(699555450)
                        },
                        new
                        {
                            Id = 20,
                            Name = "program",
                            UnitPrice = 457.251176590682400m,
                            Duration = new TimeSpan(22173094521)
                        },
                        new
                        {
                            Id = 21,
                            Name = "copy",
                            UnitPrice = 290.512378416262800m,
                            Duration = new TimeSpan(26003407483)
                        },
                        new
                        {
                            Id = 22,
                            Name = "connect",
                            UnitPrice = 426.068212057495600m,
                            Duration = new TimeSpan(1833488178)
                        },
                        new
                        {
                            Id = 23,
                            Name = "transmit",
                            UnitPrice = 176.480701601356400m,
                            Duration = new TimeSpan(49854213417)
                        },
                        new
                        {
                            Id = 24,
                            Name = "copy",
                            UnitPrice = 217.426055165671600m,
                            Duration = new TimeSpan(20721893547)
                        },
                        new
                        {
                            Id = 25,
                            Name = "calculate",
                            UnitPrice = 379.927377533133600m,
                            Duration = new TimeSpan(10953150110)
                        },
                        new
                        {
                            Id = 26,
                            Name = "copy",
                            UnitPrice = 475.458021636800m,
                            Duration = new TimeSpan(40670680881)
                        },
                        new
                        {
                            Id = 27,
                            Name = "parse",
                            UnitPrice = 149.296020925648400m,
                            Duration = new TimeSpan(12012127066)
                        },
                        new
                        {
                            Id = 28,
                            Name = "generate",
                            UnitPrice = 373.159755148533600m,
                            Duration = new TimeSpan(53571560922)
                        },
                        new
                        {
                            Id = 29,
                            Name = "connect",
                            UnitPrice = 302.313079592917600m,
                            Duration = new TimeSpan(28043610794)
                        },
                        new
                        {
                            Id = 30,
                            Name = "compress",
                            UnitPrice = 423.808911779806400m,
                            Duration = new TimeSpan(33366415427)
                        },
                        new
                        {
                            Id = 31,
                            Name = "synthesize",
                            UnitPrice = 235.82838780052400m,
                            Duration = new TimeSpan(45396098121)
                        },
                        new
                        {
                            Id = 32,
                            Name = "bypass",
                            UnitPrice = 306.103414579342800m,
                            Duration = new TimeSpan(25502445203)
                        },
                        new
                        {
                            Id = 33,
                            Name = "hack",
                            UnitPrice = 325.793171965420800m,
                            Duration = new TimeSpan(2756991116)
                        },
                        new
                        {
                            Id = 34,
                            Name = "transmit",
                            UnitPrice = 218.099743741610800m,
                            Duration = new TimeSpan(69278878200)
                        },
                        new
                        {
                            Id = 35,
                            Name = "index",
                            UnitPrice = 318.557580103426000m,
                            Duration = new TimeSpan(24135692105)
                        },
                        new
                        {
                            Id = 36,
                            Name = "hack",
                            UnitPrice = 205.575818431366000m,
                            Duration = new TimeSpan(25323452276)
                        },
                        new
                        {
                            Id = 37,
                            Name = "connect",
                            UnitPrice = 354.14883413079600m,
                            Duration = new TimeSpan(71027888093)
                        },
                        new
                        {
                            Id = 38,
                            Name = "connect",
                            UnitPrice = 461.999829654581600m,
                            Duration = new TimeSpan(55431928020)
                        },
                        new
                        {
                            Id = 39,
                            Name = "hack",
                            UnitPrice = 393.459471638062800m,
                            Duration = new TimeSpan(57123472188)
                        },
                        new
                        {
                            Id = 40,
                            Name = "calculate",
                            UnitPrice = 111.4939538815496400m,
                            Duration = new TimeSpan(22275923844)
                        },
                        new
                        {
                            Id = 41,
                            Name = "calculate",
                            UnitPrice = 318.211197395907200m,
                            Duration = new TimeSpan(27480922168)
                        },
                        new
                        {
                            Id = 42,
                            Name = "compress",
                            UnitPrice = 344.695294948618400m,
                            Duration = new TimeSpan(68687580126)
                        },
                        new
                        {
                            Id = 43,
                            Name = "calculate",
                            UnitPrice = 318.679488179590400m,
                            Duration = new TimeSpan(13288313332)
                        },
                        new
                        {
                            Id = 44,
                            Name = "transmit",
                            UnitPrice = 176.866586728425200m,
                            Duration = new TimeSpan(26939672941)
                        },
                        new
                        {
                            Id = 45,
                            Name = "generate",
                            UnitPrice = 153.472592147752800m,
                            Duration = new TimeSpan(59615329893)
                        },
                        new
                        {
                            Id = 46,
                            Name = "override",
                            UnitPrice = 160.147297969156400m,
                            Duration = new TimeSpan(9828391508)
                        },
                        new
                        {
                            Id = 47,
                            Name = "index",
                            UnitPrice = 216.259390914933600m,
                            Duration = new TimeSpan(17412707009)
                        },
                        new
                        {
                            Id = 48,
                            Name = "back up",
                            UnitPrice = 421.072746217750400m,
                            Duration = new TimeSpan(12538813977)
                        },
                        new
                        {
                            Id = 49,
                            Name = "connect",
                            UnitPrice = 198.838259325753200m,
                            Duration = new TimeSpan(31289140466)
                        },
                        new
                        {
                            Id = 50,
                            Name = "program",
                            UnitPrice = 471.439407938830400m,
                            Duration = new TimeSpan(56275909729)
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.OwnsOne("Altkom.Shop.Models.Address", "InvoiceAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("InvoiceAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Altkom.Shop.Models.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("ShippingAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Altkom.Shop.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
