// <auto-generated />
using System;
using Altkom.Shop.DbRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Altkom.Shop.DbRepositories.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20190913010252_ChangeAddresses")]
    partial class ChangeAddresses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime?>("DeliveredDate");

                    b.Property<string>("Number");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<short>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Product", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<string>("Barcode");

                    b.Property<string>("Color")
                        .HasMaxLength(20);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasDiscriminator().HasValue("Product");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Name = "Generic Cotton Tuna",
                            UnitPrice = 47.920179231520804m,
                            Barcode = "1612548488555",
                            Color = "violet",
                            SerialNumber = "06067274"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Awesome Rubber Shirt",
                            UnitPrice = 35.675093524006738m,
                            Barcode = "2560281071772",
                            Color = "lime",
                            SerialNumber = "23531703"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Intelligent Steel Soap",
                            UnitPrice = 87.179463225034696m,
                            Barcode = "1813618524009",
                            Color = "ivory",
                            SerialNumber = "87197587"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Refined Concrete Pants",
                            UnitPrice = 83.737886810087575m,
                            Barcode = "6438505188932",
                            Color = "grey",
                            SerialNumber = "77463159"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Incredible Cotton Towels",
                            UnitPrice = 94.937494222511335m,
                            Barcode = "5166278858721",
                            Color = "maroon",
                            SerialNumber = "80019817"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Refined Fresh Bike",
                            UnitPrice = 88.781209952561785m,
                            Barcode = "1157750289236",
                            Color = "red",
                            SerialNumber = "48819084"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Small Concrete Fish",
                            UnitPrice = 95.70880515440773m,
                            Barcode = "0394265785506",
                            Color = "white",
                            SerialNumber = "11008439"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Refined Metal Cheese",
                            UnitPrice = 86.043723764384044m,
                            Barcode = "9097039943645",
                            Color = "yellow",
                            SerialNumber = "65913550"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Gorgeous Fresh Chips",
                            UnitPrice = 85.70325581529328m,
                            Barcode = "9805874457520",
                            Color = "indigo",
                            SerialNumber = "68655655"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Awesome Rubber Pants",
                            UnitPrice = 84.414890661097501m,
                            Barcode = "5163188101725",
                            Color = "black",
                            SerialNumber = "24069298"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Small Soft Towels",
                            UnitPrice = 48.307616134783048m,
                            Barcode = "8926212348063",
                            Color = "sky blue",
                            SerialNumber = "10269312"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Ergonomic Cotton Bike",
                            UnitPrice = 47.201401303616053m,
                            Barcode = "5993752760412",
                            Color = "purple",
                            SerialNumber = "62999489"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Fantastic Cotton Hat",
                            UnitPrice = 10.7957204798216599m,
                            Barcode = "9296504471038",
                            Color = "gold",
                            SerialNumber = "19695204"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Generic Steel Chair",
                            UnitPrice = 51.841331064627202m,
                            Barcode = "4156677130345",
                            Color = "magenta",
                            SerialNumber = "66256045"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Intelligent Rubber Cheese",
                            UnitPrice = 10.0165062681848638m,
                            Barcode = "7891442922134",
                            Color = "red",
                            SerialNumber = "58793893"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Awesome Wooden Ball",
                            UnitPrice = 41.267141126220646m,
                            Barcode = "0446654845879",
                            Color = "cyan",
                            SerialNumber = "85798427"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Practical Fresh Car",
                            UnitPrice = 99.010979426098486m,
                            Barcode = "2413664660097",
                            Color = "indigo",
                            SerialNumber = "95277394"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Unbranded Steel Computer",
                            UnitPrice = 80.95359080655199m,
                            Barcode = "1021984236314",
                            Color = "indigo",
                            SerialNumber = "31170215"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Sleek Soft Chair",
                            UnitPrice = 24.465302333918038m,
                            Barcode = "1561808133264",
                            Color = "black",
                            SerialNumber = "43676859"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Gorgeous Wooden Gloves",
                            UnitPrice = 4.1762587740906781m,
                            Barcode = "1296932399933",
                            Color = "orchid",
                            SerialNumber = "23338173"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Refined Granite Bike",
                            UnitPrice = 58.416623036571106m,
                            Barcode = "5426170920965",
                            Color = "magenta",
                            SerialNumber = "12200962"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Fantastic Plastic Hat",
                            UnitPrice = 19.45481309688412m,
                            Barcode = "5240327602050",
                            Color = "black",
                            SerialNumber = "16128910"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Fantastic Soft Mouse",
                            UnitPrice = 91.365305824841014m,
                            Barcode = "8799863299097",
                            Color = "salmon",
                            SerialNumber = "39692351"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Rustic Soft Sausages",
                            UnitPrice = 18.698335359198175m,
                            Barcode = "7474139718168",
                            Color = "grey",
                            SerialNumber = "38749858"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Generic Concrete Pizza",
                            UnitPrice = 51.764756482450648m,
                            Barcode = "3290124176140",
                            Color = "cyan",
                            SerialNumber = "99150389"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Licensed Steel Soap",
                            UnitPrice = 69.48197182709443m,
                            Barcode = "6103177568084",
                            Color = "violet",
                            SerialNumber = "39584083"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Handcrafted Plastic Shoes",
                            UnitPrice = 8.5847207156870149m,
                            Barcode = "6912330364407",
                            Color = "silver",
                            SerialNumber = "20908577"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Refined Plastic Mouse",
                            UnitPrice = 91.408672027480114m,
                            Barcode = "7907187260711",
                            Color = "blue",
                            SerialNumber = "54127715"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Sleek Granite Soap",
                            UnitPrice = 23.318114237076691m,
                            Barcode = "1881541370543",
                            Color = "grey",
                            SerialNumber = "23177130"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Incredible Soft Shirt",
                            UnitPrice = 51.664666328422993m,
                            Barcode = "3530125137635",
                            Color = "grey",
                            SerialNumber = "06728342"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Unbranded Soft Chair",
                            UnitPrice = 55.666798012175932m,
                            Barcode = "6313130344703",
                            Color = "violet",
                            SerialNumber = "10244302"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Handmade Soft Fish",
                            UnitPrice = 61.468456187969236m,
                            Barcode = "4130394548478",
                            Color = "yellow",
                            SerialNumber = "12006298"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Refined Metal Computer",
                            UnitPrice = 24.027423082863661m,
                            Barcode = "0905747860996",
                            Color = "indigo",
                            SerialNumber = "00050159"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Handcrafted Granite Shirt",
                            UnitPrice = 5.0731407408943108m,
                            Barcode = "3084712705931",
                            Color = "black",
                            SerialNumber = "88801513"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Gorgeous Steel Chips",
                            UnitPrice = 46.83706571340424m,
                            Barcode = "1466181657263",
                            Color = "orchid",
                            SerialNumber = "52057199"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Ergonomic Metal Soap",
                            UnitPrice = 16.601111963671168m,
                            Barcode = "2501339202335",
                            Color = "yellow",
                            SerialNumber = "56614282"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Generic Concrete Table",
                            UnitPrice = 33.921716826931471m,
                            Barcode = "4521155484355",
                            Color = "azure",
                            SerialNumber = "80217060"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Refined Soft Chair",
                            UnitPrice = 2.3099565847357495m,
                            Barcode = "5708844011682",
                            Color = "mint green",
                            SerialNumber = "08057846"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Gorgeous Wooden Pants",
                            UnitPrice = 66.072847790118718m,
                            Barcode = "0646600750541",
                            Color = "grey",
                            SerialNumber = "47630345"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Fantastic Cotton Computer",
                            UnitPrice = 3.8686526673234364m,
                            Barcode = "9059209436715",
                            Color = "fuchsia",
                            SerialNumber = "08400932"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Incredible Rubber Car",
                            UnitPrice = 80.750160323339572m,
                            Barcode = "2109670655652",
                            Color = "green",
                            SerialNumber = "40441108"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Tasty Granite Pants",
                            UnitPrice = 46.927315077244876m,
                            Barcode = "8354005305717",
                            Color = "purple",
                            SerialNumber = "00766050"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Gorgeous Frozen Towels",
                            UnitPrice = 92.927484936047134m,
                            Barcode = "4891520778021",
                            Color = "red",
                            SerialNumber = "16550254"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Fantastic Plastic Shoes",
                            UnitPrice = 16.226326319494411m,
                            Barcode = "4418988985923",
                            Color = "yellow",
                            SerialNumber = "13874933"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Unbranded Cotton Hat",
                            UnitPrice = 58.60281328186528m,
                            Barcode = "5049466137702",
                            Color = "green",
                            SerialNumber = "02889146"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Handcrafted Plastic Pants",
                            UnitPrice = 38.474439854954608m,
                            Barcode = "4744932991383",
                            Color = "orchid",
                            SerialNumber = "49429794"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Generic Soft Chicken",
                            UnitPrice = 99.850931787328336m,
                            Barcode = "1517993277566",
                            Color = "black",
                            SerialNumber = "12205714"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Refined Frozen Shirt",
                            UnitPrice = 66.704505054608233m,
                            Barcode = "6269399601234",
                            Color = "green",
                            SerialNumber = "15907110"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Incredible Soft Chair",
                            UnitPrice = 3.0402466752753811m,
                            Barcode = "4988664111071",
                            Color = "magenta",
                            SerialNumber = "24977968"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Tasty Fresh Salad",
                            UnitPrice = 1.61513600946177556m,
                            Barcode = "8126777829438",
                            Color = "green",
                            SerialNumber = "11937029"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Sleek Concrete Fish",
                            UnitPrice = 31.232260733485294m,
                            Barcode = "2483207507059",
                            Color = "pink",
                            SerialNumber = "47444140"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Unbranded Granite Towels",
                            UnitPrice = 41.304939637102624m,
                            Barcode = "9238685539435",
                            Color = "olive",
                            SerialNumber = "83622830"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Rustic Granite Chips",
                            UnitPrice = 49.978304820590761m,
                            Barcode = "6853744782497",
                            Color = "lavender",
                            SerialNumber = "68911416"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Incredible Wooden Towels",
                            UnitPrice = 64.965731925315088m,
                            Barcode = "4200115423282",
                            Color = "blue",
                            SerialNumber = "22895745"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Unbranded Metal Hat",
                            UnitPrice = 33.056892940801069m,
                            Barcode = "9126346525852",
                            Color = "grey",
                            SerialNumber = "33576978"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Handcrafted Wooden Salad",
                            UnitPrice = 77.973625656205102m,
                            Barcode = "6195691777097",
                            Color = "azure",
                            SerialNumber = "98077656"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Fantastic Plastic Towels",
                            UnitPrice = 64.480657412894392m,
                            Barcode = "1799927823012",
                            Color = "yellow",
                            SerialNumber = "40933177"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Incredible Rubber Cheese",
                            UnitPrice = 62.570091306497356m,
                            Barcode = "8960515368496",
                            Color = "fuchsia",
                            SerialNumber = "92850279"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Licensed Fresh Ball",
                            UnitPrice = 61.326064659900061m,
                            Barcode = "7142598591096",
                            Color = "orchid",
                            SerialNumber = "66217657"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Handcrafted Steel Shirt",
                            UnitPrice = 85.205003438147284m,
                            Barcode = "2260810079230",
                            Color = "green",
                            SerialNumber = "63860894"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Intelligent Fresh Salad",
                            UnitPrice = 65.076146048529109m,
                            Barcode = "0581269774920",
                            Color = "orange",
                            SerialNumber = "37770020"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Fantastic Fresh Hat",
                            UnitPrice = 26.103055877659045m,
                            Barcode = "8958058433931",
                            Color = "violet",
                            SerialNumber = "29709564"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Incredible Rubber Pants",
                            UnitPrice = 98.177608552005883m,
                            Barcode = "0171529104231",
                            Color = "black",
                            SerialNumber = "11625483"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Refined Cotton Shoes",
                            UnitPrice = 83.587364773073875m,
                            Barcode = "3268220252785",
                            Color = "purple",
                            SerialNumber = "76914720"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Handcrafted Plastic Sausages",
                            UnitPrice = 84.493299073769398m,
                            Barcode = "8368734666827",
                            Color = "cyan",
                            SerialNumber = "50973989"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Incredible Fresh Table",
                            UnitPrice = 15.618644571219832m,
                            Barcode = "5750164937982",
                            Color = "azure",
                            SerialNumber = "52518119"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Licensed Metal Towels",
                            UnitPrice = 84.132935730336646m,
                            Barcode = "8447505097302",
                            Color = "pink",
                            SerialNumber = "84401892"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Ergonomic Steel Bike",
                            UnitPrice = 78.762667288893202m,
                            Barcode = "4601721912168",
                            Color = "purple",
                            SerialNumber = "17421997"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Unbranded Granite Pants",
                            UnitPrice = 61.751455524820621m,
                            Barcode = "6199672823292",
                            Color = "violet",
                            SerialNumber = "04366485"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Intelligent Fresh Pizza",
                            UnitPrice = 87.277887077665789m,
                            Barcode = "4761142925564",
                            Color = "maroon",
                            SerialNumber = "31249331"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Practical Granite Mouse",
                            UnitPrice = 48.666169389461194m,
                            Barcode = "6214572825594",
                            Color = "ivory",
                            SerialNumber = "00680363"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Unbranded Metal Pants",
                            UnitPrice = 72.450890199025579m,
                            Barcode = "1468499859582",
                            Color = "tan",
                            SerialNumber = "37353636"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Generic Plastic Table",
                            UnitPrice = 13.937438478664216m,
                            Barcode = "6571978996311",
                            Color = "azure",
                            SerialNumber = "03426647"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Sleek Fresh Hat",
                            UnitPrice = 71.929165261764601m,
                            Barcode = "9112368807182",
                            Color = "orange",
                            SerialNumber = "18980684"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Practical Concrete Table",
                            UnitPrice = 37.045776641017627m,
                            Barcode = "2009824894183",
                            Color = "red",
                            SerialNumber = "66637417"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Intelligent Granite Computer",
                            UnitPrice = 69.918494571893692m,
                            Barcode = "6608088760928",
                            Color = "gold",
                            SerialNumber = "58073391"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Handcrafted Wooden Bike",
                            UnitPrice = 52.490605945461661m,
                            Barcode = "9590008792324",
                            Color = "turquoise",
                            SerialNumber = "25815313"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Generic Plastic Bacon",
                            UnitPrice = 30.738889335533059m,
                            Barcode = "3408641546845",
                            Color = "cyan",
                            SerialNumber = "88662237"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Awesome Fresh Hat",
                            UnitPrice = 61.181787300008275m,
                            Barcode = "4702068671661",
                            Color = "indigo",
                            SerialNumber = "09150782"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Generic Plastic Pants",
                            UnitPrice = 73.832789744172568m,
                            Barcode = "6523053592482",
                            Color = "ivory",
                            SerialNumber = "39577276"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Intelligent Steel Towels",
                            UnitPrice = 76.372264559088442m,
                            Barcode = "0727091133546",
                            Color = "grey",
                            SerialNumber = "44527174"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Sleek Concrete Mouse",
                            UnitPrice = 96.933104627268898m,
                            Barcode = "2083555698227",
                            Color = "yellow",
                            SerialNumber = "25401240"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Fantastic Steel Ball",
                            UnitPrice = 59.558470486457689m,
                            Barcode = "6590288851592",
                            Color = "orange",
                            SerialNumber = "07677854"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Intelligent Plastic Sausages",
                            UnitPrice = 12.804189780170161m,
                            Barcode = "6762727285798",
                            Color = "black",
                            SerialNumber = "65319468"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Tasty Rubber Sausages",
                            UnitPrice = 52.06198219305931m,
                            Barcode = "6714461366356",
                            Color = "grey",
                            SerialNumber = "16033207"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Small Rubber Computer",
                            UnitPrice = 2.2574776104919072m,
                            Barcode = "5467682082604",
                            Color = "black",
                            SerialNumber = "02714431"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Rustic Fresh Sausages",
                            UnitPrice = 91.515785449424698m,
                            Barcode = "3377443058903",
                            Color = "grey",
                            SerialNumber = "03673270"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Small Steel Gloves",
                            UnitPrice = 17.962551291548863m,
                            Barcode = "4906211642335",
                            Color = "purple",
                            SerialNumber = "15638540"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Gorgeous Soft Computer",
                            UnitPrice = 81.751705057337743m,
                            Barcode = "7568103305253",
                            Color = "green",
                            SerialNumber = "37747251"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Tasty Plastic Chicken",
                            UnitPrice = 54.381021260926942m,
                            Barcode = "6304518780879",
                            Color = "ivory",
                            SerialNumber = "42549031"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Incredible Steel Chair",
                            UnitPrice = 31.524557704815889m,
                            Barcode = "8940120488178",
                            Color = "purple",
                            SerialNumber = "09787476"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Unbranded Steel Chair",
                            UnitPrice = 56.957585469334219m,
                            Barcode = "6199914638554",
                            Color = "turquoise",
                            SerialNumber = "78559486"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Ergonomic Fresh Shirt",
                            UnitPrice = 15.679924585707403m,
                            Barcode = "2488372899398",
                            Color = "silver",
                            SerialNumber = "31474542"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Incredible Wooden Mouse",
                            UnitPrice = 76.014420421800772m,
                            Barcode = "9234143879655",
                            Color = "fuchsia",
                            SerialNumber = "35356769"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Awesome Rubber Keyboard",
                            UnitPrice = 47.268360388590175m,
                            Barcode = "0115326129912",
                            Color = "fuchsia",
                            SerialNumber = "38655425"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Sleek Fresh Shirt",
                            UnitPrice = 36.011181329382214m,
                            Barcode = "2855543304300",
                            Color = "cyan",
                            SerialNumber = "38452529"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Generic Concrete Mouse",
                            UnitPrice = 89.96394330773686m,
                            Barcode = "1110363172258",
                            Color = "indigo",
                            SerialNumber = "71586601"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Practical Rubber Keyboard",
                            UnitPrice = 14.428346313735595m,
                            Barcode = "9729602067440",
                            Color = "ivory",
                            SerialNumber = "22931238"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Awesome Frozen Cheese",
                            UnitPrice = 98.322114570216382m,
                            Barcode = "9470123594167",
                            Color = "purple",
                            SerialNumber = "44569280"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Handcrafted Wooden Soap",
                            UnitPrice = 82.681503265016479m,
                            Barcode = "6672202990911",
                            Color = "maroon",
                            SerialNumber = "32933857"
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Service", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<TimeSpan?>("Duration");

                    b.HasDiscriminator().HasValue("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "parse",
                            UnitPrice = 273.45699880898800m,
                            Duration = new TimeSpan(37621081280)
                        },
                        new
                        {
                            Id = 2,
                            Name = "index",
                            UnitPrice = 308.14186511940400m,
                            Duration = new TimeSpan(14856009516)
                        },
                        new
                        {
                            Id = 3,
                            Name = "index",
                            UnitPrice = 215.463519336406000m,
                            Duration = new TimeSpan(42244667684)
                        },
                        new
                        {
                            Id = 4,
                            Name = "hack",
                            UnitPrice = 203.771056469423200m,
                            Duration = new TimeSpan(41281663452)
                        },
                        new
                        {
                            Id = 5,
                            Name = "quantify",
                            UnitPrice = 417.225070817966400m,
                            Duration = new TimeSpan(19829611489)
                        },
                        new
                        {
                            Id = 6,
                            Name = "reboot",
                            UnitPrice = 232.151944251801600m,
                            Duration = new TimeSpan(27461223220)
                        },
                        new
                        {
                            Id = 7,
                            Name = "hack",
                            UnitPrice = 403.546174011913200m,
                            Duration = new TimeSpan(16002156489)
                        },
                        new
                        {
                            Id = 8,
                            Name = "navigate",
                            UnitPrice = 105.7130171012659600m,
                            Duration = new TimeSpan(26777538737)
                        },
                        new
                        {
                            Id = 9,
                            Name = "index",
                            UnitPrice = 193.417525893737200m,
                            Duration = new TimeSpan(18679462125)
                        },
                        new
                        {
                            Id = 10,
                            Name = "override",
                            UnitPrice = 294.513376892783200m,
                            Duration = new TimeSpan(69444757337)
                        },
                        new
                        {
                            Id = 11,
                            Name = "back up",
                            UnitPrice = 176.248085348051200m,
                            Duration = new TimeSpan(7154292117)
                        },
                        new
                        {
                            Id = 12,
                            Name = "compress",
                            UnitPrice = 207.548011330677200m,
                            Duration = new TimeSpan(54163234807)
                        },
                        new
                        {
                            Id = 13,
                            Name = "back up",
                            UnitPrice = 328.727674218233600m,
                            Duration = new TimeSpan(67818801461)
                        },
                        new
                        {
                            Id = 14,
                            Name = "hack",
                            UnitPrice = 147.054765581644400m,
                            Duration = new TimeSpan(57480525606)
                        },
                        new
                        {
                            Id = 15,
                            Name = "transmit",
                            UnitPrice = 201.999234641901600m,
                            Duration = new TimeSpan(54600944630)
                        },
                        new
                        {
                            Id = 16,
                            Name = "input",
                            UnitPrice = 121.8711916459124400m,
                            Duration = new TimeSpan(43570201499)
                        },
                        new
                        {
                            Id = 17,
                            Name = "copy",
                            UnitPrice = 212.2695504279200m,
                            Duration = new TimeSpan(60943246549)
                        },
                        new
                        {
                            Id = 18,
                            Name = "calculate",
                            UnitPrice = 352.998791566583600m,
                            Duration = new TimeSpan(18281697401)
                        },
                        new
                        {
                            Id = 19,
                            Name = "index",
                            UnitPrice = 342.386475132026800m,
                            Duration = new TimeSpan(30193916707)
                        },
                        new
                        {
                            Id = 20,
                            Name = "hack",
                            UnitPrice = 115.6167304216030800m,
                            Duration = new TimeSpan(20650381061)
                        },
                        new
                        {
                            Id = 21,
                            Name = "parse",
                            UnitPrice = 182.630817630622000m,
                            Duration = new TimeSpan(57771025640)
                        },
                        new
                        {
                            Id = 22,
                            Name = "calculate",
                            UnitPrice = 141.583890859775200m,
                            Duration = new TimeSpan(4954134802)
                        },
                        new
                        {
                            Id = 23,
                            Name = "connect",
                            UnitPrice = 234.58134053954000m,
                            Duration = new TimeSpan(37741870708)
                        },
                        new
                        {
                            Id = 24,
                            Name = "generate",
                            UnitPrice = 452.677056916373600m,
                            Duration = new TimeSpan(54616368606)
                        },
                        new
                        {
                            Id = 25,
                            Name = "index",
                            UnitPrice = 497.326681761688800m,
                            Duration = new TimeSpan(46168453517)
                        },
                        new
                        {
                            Id = 26,
                            Name = "index",
                            UnitPrice = 336.06573335643200m,
                            Duration = new TimeSpan(54668480843)
                        },
                        new
                        {
                            Id = 27,
                            Name = "calculate",
                            UnitPrice = 359.315683440918000m,
                            Duration = new TimeSpan(12878340165)
                        },
                        new
                        {
                            Id = 28,
                            Name = "calculate",
                            UnitPrice = 457.3243694181200m,
                            Duration = new TimeSpan(14803888764)
                        },
                        new
                        {
                            Id = 29,
                            Name = "hack",
                            UnitPrice = 251.935076598047600m,
                            Duration = new TimeSpan(40184872881)
                        },
                        new
                        {
                            Id = 30,
                            Name = "program",
                            UnitPrice = 419.721626266707600m,
                            Duration = new TimeSpan(47729076516)
                        },
                        new
                        {
                            Id = 31,
                            Name = "copy",
                            UnitPrice = 461.273286101070000m,
                            Duration = new TimeSpan(38359969883)
                        },
                        new
                        {
                            Id = 32,
                            Name = "calculate",
                            UnitPrice = 178.852028622688800m,
                            Duration = new TimeSpan(65596310631)
                        },
                        new
                        {
                            Id = 33,
                            Name = "parse",
                            UnitPrice = 162.64573208179600m,
                            Duration = new TimeSpan(10874761881)
                        },
                        new
                        {
                            Id = 34,
                            Name = "synthesize",
                            UnitPrice = 206.81402557846800m,
                            Duration = new TimeSpan(51712173199)
                        },
                        new
                        {
                            Id = 35,
                            Name = "bypass",
                            UnitPrice = 412.746679928501600m,
                            Duration = new TimeSpan(28726648832)
                        },
                        new
                        {
                            Id = 36,
                            Name = "bypass",
                            UnitPrice = 183.002177664545600m,
                            Duration = new TimeSpan(46020979765)
                        },
                        new
                        {
                            Id = 37,
                            Name = "calculate",
                            UnitPrice = 499.760194681473200m,
                            Duration = new TimeSpan(1137733520)
                        },
                        new
                        {
                            Id = 38,
                            Name = "calculate",
                            UnitPrice = 314.816380205944400m,
                            Duration = new TimeSpan(28134188457)
                        },
                        new
                        {
                            Id = 39,
                            Name = "bypass",
                            UnitPrice = 217.040482031666000m,
                            Duration = new TimeSpan(22555160678)
                        },
                        new
                        {
                            Id = 40,
                            Name = "quantify",
                            UnitPrice = 301.657775324610000m,
                            Duration = new TimeSpan(52136786567)
                        },
                        new
                        {
                            Id = 41,
                            Name = "generate",
                            UnitPrice = 351.415425656091200m,
                            Duration = new TimeSpan(38674748569)
                        },
                        new
                        {
                            Id = 42,
                            Name = "program",
                            UnitPrice = 176.094769908159200m,
                            Duration = new TimeSpan(70452678747)
                        },
                        new
                        {
                            Id = 43,
                            Name = "compress",
                            UnitPrice = 413.744451996751200m,
                            Duration = new TimeSpan(57325437565)
                        },
                        new
                        {
                            Id = 44,
                            Name = "input",
                            UnitPrice = 271.178505090614000m,
                            Duration = new TimeSpan(31215600229)
                        },
                        new
                        {
                            Id = 45,
                            Name = "quantify",
                            UnitPrice = 469.609912656997200m,
                            Duration = new TimeSpan(27450298415)
                        },
                        new
                        {
                            Id = 46,
                            Name = "connect",
                            UnitPrice = 329.338499079150400m,
                            Duration = new TimeSpan(8023984108)
                        },
                        new
                        {
                            Id = 47,
                            Name = "transmit",
                            UnitPrice = 112.0812935810914800m,
                            Duration = new TimeSpan(12407921808)
                        },
                        new
                        {
                            Id = 48,
                            Name = "reboot",
                            UnitPrice = 193.107504627251600m,
                            Duration = new TimeSpan(57593057685)
                        },
                        new
                        {
                            Id = 49,
                            Name = "calculate",
                            UnitPrice = 369.132679081118000m,
                            Duration = new TimeSpan(26362243061)
                        },
                        new
                        {
                            Id = 50,
                            Name = "hack",
                            UnitPrice = 318.868775022620800m,
                            Duration = new TimeSpan(65126078386)
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.OwnsOne("Altkom.Shop.Models.Address", "InvoiceAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("InvoiceAddresses");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("InvoiceAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Altkom.Shop.Models.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("ShippingAddresses");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("ShippingAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Altkom.Shop.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
