// <auto-generated />
using System;
using Altkom.Shop.DbRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Altkom.Shop.DbRepositories.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20190913035613_AddRowVersionToCustomer")]
    partial class AddRowVersionToCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime?>("DeliveredDate");

                    b.Property<string>("Number");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<short>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Altkom.Shop.Models.Product", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<string>("Barcode");

                    b.Property<string>("Color")
                        .HasMaxLength(20);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasDiscriminator().HasValue("Product");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Name = "Handcrafted Wooden Gloves",
                            UnitPrice = 69.938194684655494m,
                            Barcode = "1646857182040",
                            Color = "silver",
                            SerialNumber = "41155134"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Unbranded Soft Chair",
                            UnitPrice = 36.378708593258008m,
                            Barcode = "9667075291460",
                            Color = "magenta",
                            SerialNumber = "98022618"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Handcrafted Steel Chicken",
                            UnitPrice = 30.757852025217316m,
                            Barcode = "6855860367619",
                            Color = "grey",
                            SerialNumber = "99107758"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Generic Granite Soap",
                            UnitPrice = 24.822890060405689m,
                            Barcode = "1042660992119",
                            Color = "ivory",
                            SerialNumber = "19430195"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Rustic Fresh Gloves",
                            UnitPrice = 64.023615534428362m,
                            Barcode = "4169437028370",
                            Color = "grey",
                            SerialNumber = "27797617"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Licensed Frozen Sausages",
                            UnitPrice = 32.97107784262447m,
                            Barcode = "2225535270850",
                            Color = "lime",
                            SerialNumber = "00465090"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Generic Soft Computer",
                            UnitPrice = 16.455081541303162m,
                            Barcode = "4954765519726",
                            Color = "white",
                            SerialNumber = "02582191"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Tasty Concrete Chips",
                            UnitPrice = 11.546283158728075m,
                            Barcode = "2506961410158",
                            Color = "magenta",
                            SerialNumber = "81514236"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Gorgeous Plastic Hat",
                            UnitPrice = 8.6877660479805262m,
                            Barcode = "5114892208217",
                            Color = "pink",
                            SerialNumber = "58558201"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Ergonomic Frozen Chair",
                            UnitPrice = 1.84478000218271308m,
                            Barcode = "6867884907184",
                            Color = "blue",
                            SerialNumber = "56617856"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Refined Plastic Hat",
                            UnitPrice = 87.387389748537625m,
                            Barcode = "6829242510702",
                            Color = "salmon",
                            SerialNumber = "25314311"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Handmade Soft Chair",
                            UnitPrice = 50.819559520026439m,
                            Barcode = "6832492321004",
                            Color = "purple",
                            SerialNumber = "54654570"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Unbranded Rubber Sausages",
                            UnitPrice = 13.003351267894426m,
                            Barcode = "5354168971333",
                            Color = "mint green",
                            SerialNumber = "10117477"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Awesome Cotton Soap",
                            UnitPrice = 40.224768850125694m,
                            Barcode = "6541952991601",
                            Color = "silver",
                            SerialNumber = "37163020"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ergonomic Plastic Table",
                            UnitPrice = 93.831542625013489m,
                            Barcode = "4675886176857",
                            Color = "maroon",
                            SerialNumber = "26929347"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Fantastic Steel Fish",
                            UnitPrice = 76.872980406914416m,
                            Barcode = "2174128319738",
                            Color = "red",
                            SerialNumber = "77015532"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Tasty Rubber Pants",
                            UnitPrice = 26.06255537227849m,
                            Barcode = "1947850497279",
                            Color = "magenta",
                            SerialNumber = "01957440"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Refined Rubber Table",
                            UnitPrice = 8.1140912776412875m,
                            Barcode = "2337690571212",
                            Color = "white",
                            SerialNumber = "71569345"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Practical Plastic Computer",
                            UnitPrice = 91.542488223194326m,
                            Barcode = "6805218551443",
                            Color = "grey",
                            SerialNumber = "12796601"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Unbranded Soft Fish",
                            UnitPrice = 57.977276730340582m,
                            Barcode = "8735138920181",
                            Color = "salmon",
                            SerialNumber = "95362762"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Handmade Steel Hat",
                            UnitPrice = 11.041530108564295m,
                            Barcode = "6447214814643",
                            Color = "olive",
                            SerialNumber = "82313425"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Ergonomic Frozen Car",
                            UnitPrice = 48.310370868216412m,
                            Barcode = "3461118826970",
                            Color = "purple",
                            SerialNumber = "91705372"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Refined Frozen Bacon",
                            UnitPrice = 16.919878532607082m,
                            Barcode = "3422845732484",
                            Color = "red",
                            SerialNumber = "53695819"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Fantastic Metal Bike",
                            UnitPrice = 68.412279261468097m,
                            Barcode = "7157252366873",
                            Color = "black",
                            SerialNumber = "96080238"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Handcrafted Fresh Towels",
                            UnitPrice = 93.960992461052287m,
                            Barcode = "7780766629464",
                            Color = "white",
                            SerialNumber = "88480015"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Sleek Fresh Chips",
                            UnitPrice = 3.1957497755977069m,
                            Barcode = "8201355853040",
                            Color = "silver",
                            SerialNumber = "62599153"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Rustic Plastic Chair",
                            UnitPrice = 54.414589316311531m,
                            Barcode = "7566667879241",
                            Color = "black",
                            SerialNumber = "55363501"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Licensed Steel Computer",
                            UnitPrice = 79.074191520490726m,
                            Barcode = "4293398428488",
                            Color = "gold",
                            SerialNumber = "89195178"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Tasty Steel Shirt",
                            UnitPrice = 77.506348321450135m,
                            Barcode = "8865244648140",
                            Color = "violet",
                            SerialNumber = "64570723"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Ergonomic Granite Cheese",
                            UnitPrice = 5.3714854942501897m,
                            Barcode = "3196338385449",
                            Color = "maroon",
                            SerialNumber = "32283747"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Licensed Metal Pants",
                            UnitPrice = 7.7788701149536576m,
                            Barcode = "5971863312218",
                            Color = "purple",
                            SerialNumber = "57309767"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Tasty Wooden Shoes",
                            UnitPrice = 6.2922918057498973m,
                            Barcode = "5343076678144",
                            Color = "gold",
                            SerialNumber = "66512035"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Small Steel Gloves",
                            UnitPrice = 68.430999139990156m,
                            Barcode = "3300021448643",
                            Color = "salmon",
                            SerialNumber = "19336541"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Handcrafted Frozen Shoes",
                            UnitPrice = 74.145146089207951m,
                            Barcode = "2488747408972",
                            Color = "pink",
                            SerialNumber = "66646693"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Small Steel Chips",
                            UnitPrice = 32.271400721404459m,
                            Barcode = "7945668487752",
                            Color = "white",
                            SerialNumber = "42600138"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Tasty Rubber Chicken",
                            UnitPrice = 96.833623506516973m,
                            Barcode = "9900073256186",
                            Color = "silver",
                            SerialNumber = "92840584"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Refined Steel Chair",
                            UnitPrice = 83.288879044488424m,
                            Barcode = "9968662124568",
                            Color = "pink",
                            SerialNumber = "58413500"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Rustic Fresh Car",
                            UnitPrice = 55.433578836002212m,
                            Barcode = "3933771896008",
                            Color = "indigo",
                            SerialNumber = "04583059"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Handmade Wooden Pizza",
                            UnitPrice = 89.125216020329455m,
                            Barcode = "1752012188564",
                            Color = "mint green",
                            SerialNumber = "38352676"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Licensed Plastic Chair",
                            UnitPrice = 23.76011961827065m,
                            Barcode = "0140340101200",
                            Color = "azure",
                            SerialNumber = "18874822"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Unbranded Fresh Shoes",
                            UnitPrice = 22.922951172070069m,
                            Barcode = "6920493876286",
                            Color = "turquoise",
                            SerialNumber = "61837461"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Handcrafted Plastic Table",
                            UnitPrice = 47.904283052731423m,
                            Barcode = "8949080170338",
                            Color = "violet",
                            SerialNumber = "20617332"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Awesome Steel Computer",
                            UnitPrice = 65.152816104773836m,
                            Barcode = "0844228348151",
                            Color = "orange",
                            SerialNumber = "54786110"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Handmade Granite Computer",
                            UnitPrice = 42.060254674898602m,
                            Barcode = "7442098780922",
                            Color = "lime",
                            SerialNumber = "35942085"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Refined Wooden Towels",
                            UnitPrice = 46.047904726605814m,
                            Barcode = "6484945577775",
                            Color = "grey",
                            SerialNumber = "85259461"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Sleek Granite Hat",
                            UnitPrice = 62.044674643801882m,
                            Barcode = "2646678590665",
                            Color = "blue",
                            SerialNumber = "13835347"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Licensed Wooden Soap",
                            UnitPrice = 74.899776765564343m,
                            Barcode = "7344518087225",
                            Color = "lime",
                            SerialNumber = "08908186"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Refined Metal Shirt",
                            UnitPrice = 39.549025800800416m,
                            Barcode = "5391092007929",
                            Color = "plum",
                            SerialNumber = "24082679"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Ergonomic Rubber Pants",
                            UnitPrice = 33.510290346811684m,
                            Barcode = "3476388198924",
                            Color = "olive",
                            SerialNumber = "16094215"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Tasty Metal Cheese",
                            UnitPrice = 45.025170373742041m,
                            Barcode = "1952895992757",
                            Color = "turquoise",
                            SerialNumber = "16728721"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Sleek Fresh Tuna",
                            UnitPrice = 94.814450922335671m,
                            Barcode = "6898407672531",
                            Color = "salmon",
                            SerialNumber = "36293926"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Unbranded Cotton Cheese",
                            UnitPrice = 89.680387860946486m,
                            Barcode = "5951439239507",
                            Color = "gold",
                            SerialNumber = "06495084"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Rustic Plastic Pizza",
                            UnitPrice = 42.989007831080365m,
                            Barcode = "5215666100352",
                            Color = "purple",
                            SerialNumber = "55243292"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Ergonomic Wooden Sausages",
                            UnitPrice = 98.928488909233576m,
                            Barcode = "4248587103615",
                            Color = "magenta",
                            SerialNumber = "14662300"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Gorgeous Frozen Table",
                            UnitPrice = 16.030036199386252m,
                            Barcode = "8458340334033",
                            Color = "red",
                            SerialNumber = "28613145"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Refined Wooden Bike",
                            UnitPrice = 77.077794088552564m,
                            Barcode = "5217194584901",
                            Color = "azure",
                            SerialNumber = "38763373"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Fantastic Plastic Table",
                            UnitPrice = 84.552401209973014m,
                            Barcode = "7961521726318",
                            Color = "grey",
                            SerialNumber = "23240544"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Refined Rubber Bacon",
                            UnitPrice = 69.040361711308492m,
                            Barcode = "3784345287926",
                            Color = "salmon",
                            SerialNumber = "32952278"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Sleek Metal Shirt",
                            UnitPrice = 47.974832211609379m,
                            Barcode = "1378855100787",
                            Color = "silver",
                            SerialNumber = "47380127"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Incredible Steel Computer",
                            UnitPrice = 30.122695412543953m,
                            Barcode = "5955710738390",
                            Color = "lime",
                            SerialNumber = "67322817"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Awesome Wooden Computer",
                            UnitPrice = 57.83274217594072m,
                            Barcode = "9963496120298",
                            Color = "sky blue",
                            SerialNumber = "99399047"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Fantastic Cotton Keyboard",
                            UnitPrice = 67.076647620683788m,
                            Barcode = "7914881370684",
                            Color = "grey",
                            SerialNumber = "57242170"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Fantastic Plastic Gloves",
                            UnitPrice = 92.662849397707192m,
                            Barcode = "5135751482647",
                            Color = "pink",
                            SerialNumber = "71248912"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Gorgeous Granite Table",
                            UnitPrice = 29.402525619325495m,
                            Barcode = "7932649468978",
                            Color = "teal",
                            SerialNumber = "46629197"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Ergonomic Soft Fish",
                            UnitPrice = 85.025092860229807m,
                            Barcode = "9285130071873",
                            Color = "yellow",
                            SerialNumber = "29732180"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Rustic Granite Chips",
                            UnitPrice = 30.536120808933013m,
                            Barcode = "2901510922340",
                            Color = "white",
                            SerialNumber = "64228907"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Licensed Fresh Chair",
                            UnitPrice = 2.4498827059054195m,
                            Barcode = "3509999435215",
                            Color = "silver",
                            SerialNumber = "39450951"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Generic Cotton Fish",
                            UnitPrice = 10.5845627284536844m,
                            Barcode = "9501564390794",
                            Color = "gold",
                            SerialNumber = "11932901"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Intelligent Steel Sausages",
                            UnitPrice = 32.250850331620744m,
                            Barcode = "4428303981943",
                            Color = "gold",
                            SerialNumber = "87960921"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Gorgeous Granite Shoes",
                            UnitPrice = 93.549768408085087m,
                            Barcode = "9277266862609",
                            Color = "cyan",
                            SerialNumber = "46096708"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Intelligent Granite Shoes",
                            UnitPrice = 64.69946171049934m,
                            Barcode = "9402865993809",
                            Color = "turquoise",
                            SerialNumber = "26725185"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Ergonomic Fresh Mouse",
                            UnitPrice = 7.9630684512495436m,
                            Barcode = "9365456473787",
                            Color = "turquoise",
                            SerialNumber = "63006711"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Handmade Fresh Chicken",
                            UnitPrice = 91.302241814463547m,
                            Barcode = "0830683125345",
                            Color = "green",
                            SerialNumber = "90546334"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Unbranded Fresh Soap",
                            UnitPrice = 5.8663771934185045m,
                            Barcode = "0703616066452",
                            Color = "teal",
                            SerialNumber = "15799555"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Small Rubber Car",
                            UnitPrice = 37.379817309034936m,
                            Barcode = "1633571121080",
                            Color = "sky blue",
                            SerialNumber = "79418386"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Generic Frozen Ball",
                            UnitPrice = 98.574835581041302m,
                            Barcode = "5393351475203",
                            Color = "yellow",
                            SerialNumber = "73484332"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Awesome Fresh Mouse",
                            UnitPrice = 29.187590395653469m,
                            Barcode = "0416769142729",
                            Color = "lavender",
                            SerialNumber = "87869514"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Licensed Granite Shirt",
                            UnitPrice = 47.556754263842878m,
                            Barcode = "9982625610387",
                            Color = "sky blue",
                            SerialNumber = "35705055"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Awesome Concrete Chair",
                            UnitPrice = 80.568157567907206m,
                            Barcode = "4609781506778",
                            Color = "ivory",
                            SerialNumber = "86517003"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Fantastic Frozen Gloves",
                            UnitPrice = 73.755355710981097m,
                            Barcode = "8077899791700",
                            Color = "turquoise",
                            SerialNumber = "25938784"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Licensed Frozen Ball",
                            UnitPrice = 69.822688995312274m,
                            Barcode = "5474123535063",
                            Color = "azure",
                            SerialNumber = "14616082"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Unbranded Granite Bacon",
                            UnitPrice = 74.336323206469609m,
                            Barcode = "1796156988246",
                            Color = "purple",
                            SerialNumber = "15577269"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Sleek Plastic Keyboard",
                            UnitPrice = 37.343285454597022m,
                            Barcode = "0707150965349",
                            Color = "maroon",
                            SerialNumber = "27378175"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Intelligent Concrete Sausages",
                            UnitPrice = 58.435905709600066m,
                            Barcode = "4096806855544",
                            Color = "mint green",
                            SerialNumber = "49827279"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Rustic Wooden Shoes",
                            UnitPrice = 71.895354303016936m,
                            Barcode = "8883572878206",
                            Color = "red",
                            SerialNumber = "63159585"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Rustic Frozen Gloves",
                            UnitPrice = 60.10213694120857m,
                            Barcode = "3559430369708",
                            Color = "lavender",
                            SerialNumber = "23283763"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Generic Soft Chicken",
                            UnitPrice = 67.203826732097164m,
                            Barcode = "1265278959903",
                            Color = "violet",
                            SerialNumber = "12338948"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Generic Wooden Gloves",
                            UnitPrice = 31.165246512352171m,
                            Barcode = "2034263581820",
                            Color = "salmon",
                            SerialNumber = "74180844"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Fantastic Concrete Soap",
                            UnitPrice = 5.4683047279102276m,
                            Barcode = "4276308090319",
                            Color = "blue",
                            SerialNumber = "34685310"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Practical Wooden Tuna",
                            UnitPrice = 62.716552168930219m,
                            Barcode = "7557601042098",
                            Color = "violet",
                            SerialNumber = "96283837"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Rustic Steel Hat",
                            UnitPrice = 9.1990628750990476m,
                            Barcode = "2570056262984",
                            Color = "olive",
                            SerialNumber = "40389363"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Practical Metal Salad",
                            UnitPrice = 68.292725029072147m,
                            Barcode = "1375703709406",
                            Color = "azure",
                            SerialNumber = "21986734"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Handmade Cotton Shirt",
                            UnitPrice = 50.539542376315024m,
                            Barcode = "4468342668870",
                            Color = "teal",
                            SerialNumber = "80559184"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Generic Concrete Soap",
                            UnitPrice = 49.615136263712854m,
                            Barcode = "3746222794033",
                            Color = "indigo",
                            SerialNumber = "34456842"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Intelligent Concrete Car",
                            UnitPrice = 35.699827577313349m,
                            Barcode = "1765586288455",
                            Color = "tan",
                            SerialNumber = "95345178"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Small Concrete Bike",
                            UnitPrice = 45.741459199106989m,
                            Barcode = "7287805179459",
                            Color = "tan",
                            SerialNumber = "56118841"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Small Fresh Soap",
                            UnitPrice = 1.19065051162180045m,
                            Barcode = "5980465951732",
                            Color = "purple",
                            SerialNumber = "08473271"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Small Fresh Sausages",
                            UnitPrice = 34.73142649779628m,
                            Barcode = "0641774966187",
                            Color = "azure",
                            SerialNumber = "15604590"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Tasty Fresh Chair",
                            UnitPrice = 39.958843743409447m,
                            Barcode = "3618060709084",
                            Color = "red",
                            SerialNumber = "23177864"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Handcrafted Rubber Towels",
                            UnitPrice = 21.521787855085792m,
                            Barcode = "5755869154818",
                            Color = "gold",
                            SerialNumber = "66805489"
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Service", b =>
                {
                    b.HasBaseType("Altkom.Shop.Models.Item");

                    b.Property<TimeSpan?>("Duration");

                    b.HasDiscriminator().HasValue("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "hack",
                            UnitPrice = 342.579366007158400m,
                            Duration = new TimeSpan(43527942860)
                        },
                        new
                        {
                            Id = 2,
                            Name = "calculate",
                            UnitPrice = 391.794901104548400m,
                            Duration = new TimeSpan(10001475428)
                        },
                        new
                        {
                            Id = 3,
                            Name = "transmit",
                            UnitPrice = 188.921405416411200m,
                            Duration = new TimeSpan(31450364396)
                        },
                        new
                        {
                            Id = 4,
                            Name = "reboot",
                            UnitPrice = 165.460359894419200m,
                            Duration = new TimeSpan(56704326872)
                        },
                        new
                        {
                            Id = 5,
                            Name = "calculate",
                            UnitPrice = 492.961379323602400m,
                            Duration = new TimeSpan(1056782239)
                        },
                        new
                        {
                            Id = 6,
                            Name = "bypass",
                            UnitPrice = 255.652345975699200m,
                            Duration = new TimeSpan(26345247881)
                        },
                        new
                        {
                            Id = 7,
                            Name = "back up",
                            UnitPrice = 131.62546885741200m,
                            Duration = new TimeSpan(33730074287)
                        },
                        new
                        {
                            Id = 8,
                            Name = "override",
                            UnitPrice = 268.482021693364800m,
                            Duration = new TimeSpan(12729315425)
                        },
                        new
                        {
                            Id = 9,
                            Name = "connect",
                            UnitPrice = 327.127495886351600m,
                            Duration = new TimeSpan(35480410164)
                        },
                        new
                        {
                            Id = 10,
                            Name = "copy",
                            UnitPrice = 343.417557628554000m,
                            Duration = new TimeSpan(33907384363)
                        },
                        new
                        {
                            Id = 11,
                            Name = "program",
                            UnitPrice = 348.960286308527200m,
                            Duration = new TimeSpan(16141082376)
                        },
                        new
                        {
                            Id = 12,
                            Name = "hack",
                            UnitPrice = 188.588234637206400m,
                            Duration = new TimeSpan(52721115055)
                        },
                        new
                        {
                            Id = 13,
                            Name = "synthesize",
                            UnitPrice = 292.254169002293600m,
                            Duration = new TimeSpan(38301478918)
                        },
                        new
                        {
                            Id = 14,
                            Name = "program",
                            UnitPrice = 180.263242535415600m,
                            Duration = new TimeSpan(60471183093)
                        },
                        new
                        {
                            Id = 15,
                            Name = "parse",
                            UnitPrice = 384.392676634896800m,
                            Duration = new TimeSpan(38130879226)
                        },
                        new
                        {
                            Id = 16,
                            Name = "program",
                            UnitPrice = 242.350454694754800m,
                            Duration = new TimeSpan(64709684816)
                        },
                        new
                        {
                            Id = 17,
                            Name = "program",
                            UnitPrice = 141.580803525438800m,
                            Duration = new TimeSpan(13940109803)
                        },
                        new
                        {
                            Id = 18,
                            Name = "connect",
                            UnitPrice = 457.515482025926800m,
                            Duration = new TimeSpan(18984142227)
                        },
                        new
                        {
                            Id = 19,
                            Name = "back up",
                            UnitPrice = 486.335137666359200m,
                            Duration = new TimeSpan(13337521976)
                        },
                        new
                        {
                            Id = 20,
                            Name = "index",
                            UnitPrice = 161.176506458398400m,
                            Duration = new TimeSpan(11640132939)
                        },
                        new
                        {
                            Id = 21,
                            Name = "calculate",
                            UnitPrice = 295.850531289284400m,
                            Duration = new TimeSpan(44190692602)
                        },
                        new
                        {
                            Id = 22,
                            Name = "parse",
                            UnitPrice = 129.0351590276859600m,
                            Duration = new TimeSpan(38970013245)
                        },
                        new
                        {
                            Id = 23,
                            Name = "quantify",
                            UnitPrice = 308.376772612508800m,
                            Duration = new TimeSpan(54787166044)
                        },
                        new
                        {
                            Id = 24,
                            Name = "copy",
                            UnitPrice = 258.962429575138800m,
                            Duration = new TimeSpan(65411671855)
                        },
                        new
                        {
                            Id = 25,
                            Name = "program",
                            UnitPrice = 164.046115830562000m,
                            Duration = new TimeSpan(63245200738)
                        },
                        new
                        {
                            Id = 26,
                            Name = "calculate",
                            UnitPrice = 193.612149587651600m,
                            Duration = new TimeSpan(51136082111)
                        },
                        new
                        {
                            Id = 27,
                            Name = "calculate",
                            UnitPrice = 351.894195122595200m,
                            Duration = new TimeSpan(15259867414)
                        },
                        new
                        {
                            Id = 28,
                            Name = "quantify",
                            UnitPrice = 277.861118585738000m,
                            Duration = new TimeSpan(36330615739)
                        },
                        new
                        {
                            Id = 29,
                            Name = "compress",
                            UnitPrice = 261.367042624096800m,
                            Duration = new TimeSpan(52460064771)
                        },
                        new
                        {
                            Id = 30,
                            Name = "parse",
                            UnitPrice = 143.289711346519200m,
                            Duration = new TimeSpan(18405557455)
                        },
                        new
                        {
                            Id = 31,
                            Name = "generate",
                            UnitPrice = 205.710144576481600m,
                            Duration = new TimeSpan(23593979258)
                        },
                        new
                        {
                            Id = 32,
                            Name = "navigate",
                            UnitPrice = 195.731571175033200m,
                            Duration = new TimeSpan(51194288024)
                        },
                        new
                        {
                            Id = 33,
                            Name = "compress",
                            UnitPrice = 499.212853051355600m,
                            Duration = new TimeSpan(45964353169)
                        },
                        new
                        {
                            Id = 34,
                            Name = "parse",
                            UnitPrice = 216.946833635190000m,
                            Duration = new TimeSpan(60115262775)
                        },
                        new
                        {
                            Id = 35,
                            Name = "hack",
                            UnitPrice = 325.259350717654000m,
                            Duration = new TimeSpan(50871307311)
                        },
                        new
                        {
                            Id = 36,
                            Name = "copy",
                            UnitPrice = 352.4570363818000m,
                            Duration = new TimeSpan(52824485915)
                        },
                        new
                        {
                            Id = 37,
                            Name = "navigate",
                            UnitPrice = 261.426633857854800m,
                            Duration = new TimeSpan(52690137854)
                        },
                        new
                        {
                            Id = 38,
                            Name = "connect",
                            UnitPrice = 412.223284650698000m,
                            Duration = new TimeSpan(37670816040)
                        },
                        new
                        {
                            Id = 39,
                            Name = "parse",
                            UnitPrice = 120.8352217547759600m,
                            Duration = new TimeSpan(3238094287)
                        },
                        new
                        {
                            Id = 40,
                            Name = "bypass",
                            UnitPrice = 375.420585961742400m,
                            Duration = new TimeSpan(48180260953)
                        },
                        new
                        {
                            Id = 41,
                            Name = "transmit",
                            UnitPrice = 341.14613525622800m,
                            Duration = new TimeSpan(29715671028)
                        },
                        new
                        {
                            Id = 42,
                            Name = "generate",
                            UnitPrice = 394.178189474240800m,
                            Duration = new TimeSpan(9585411300)
                        },
                        new
                        {
                            Id = 43,
                            Name = "quantify",
                            UnitPrice = 285.457905468278400m,
                            Duration = new TimeSpan(66296618038)
                        },
                        new
                        {
                            Id = 44,
                            Name = "override",
                            UnitPrice = 260.991115011736400m,
                            Duration = new TimeSpan(16991873377)
                        },
                        new
                        {
                            Id = 45,
                            Name = "bypass",
                            UnitPrice = 363.542056765194000m,
                            Duration = new TimeSpan(24290525068)
                        },
                        new
                        {
                            Id = 46,
                            Name = "navigate",
                            UnitPrice = 282.490036535304800m,
                            Duration = new TimeSpan(63468318216)
                        },
                        new
                        {
                            Id = 47,
                            Name = "transmit",
                            UnitPrice = 496.88242561970000m,
                            Duration = new TimeSpan(55603801124)
                        },
                        new
                        {
                            Id = 48,
                            Name = "parse",
                            UnitPrice = 330.099992561200800m,
                            Duration = new TimeSpan(50735353948)
                        },
                        new
                        {
                            Id = 49,
                            Name = "generate",
                            UnitPrice = 128.7897400692057600m,
                            Duration = new TimeSpan(34827634787)
                        },
                        new
                        {
                            Id = 50,
                            Name = "transmit",
                            UnitPrice = 268.22822474326400m,
                            Duration = new TimeSpan(13481342896)
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Customer", b =>
                {
                    b.OwnsOne("Altkom.Shop.Models.Address", "InvoiceAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("InvoiceAddresses");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("InvoiceAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Altkom.Shop.Models.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("PostCode");

                            b1.Property<string>("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("ShippingAddresses");

                            b1.HasOne("Altkom.Shop.Models.Customer")
                                .WithOne("ShippingAddress")
                                .HasForeignKey("Altkom.Shop.Models.Address", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Altkom.Shop.Models.Order", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Altkom.Shop.Models.OrderDetail", b =>
                {
                    b.HasOne("Altkom.Shop.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Altkom.Shop.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
